### ISSUE TITLE
How to use join queries? and update data more than one table

### ISSUE THREAD

**Issue by vijaybonzer** [serverfireteam/panel#1]
Hi I am using panel in my project. It's really great product.

But i am facing issue like i am not able to write left/right join quires. I want to display data which is fetch from more than one table. And want do same for edit.

Can you please help to solve this issue...

**Comment by siavash13** [comment]
Firstly thanks for using our package

As I've already mentioned in the wiki the package benefits from Zofe/rapyd package you can check the website http://www.rapyd.com/ in the demo of website, it's mentioned how to have join queries, but in general take the following example: 
the `Category` and `Product` model

if you need to have the Category of each product when fetching all Products, you can have the following codes:

 `$grid = DataGrid::source(Product::with('category');`

     class Product extends \Eloquent
    {
         protected $table = 'products';

         public function category()
        {
           return $this->belongsTo('Category', 'category_id');
        }
     }

**Comment by vijaybonzer** [comment]
Thanks siavash13 for the quick reply. 

But can you please post example like fetching records from more than 2 tables (use join with more than two tables).

And create form with some extra fields. Like our data is going to save in multiple tables.

**Comment by siavash13** [comment]
Ok let's say we need to obtain `material` of each product alongside  with its `category`, we need to modify the grid 

`$grid = DataGrid::source(Product::with('category','material');`

`
 class Product extends \Eloquent
{
     protected $table = 'products';

     public function category()
    {
       return $this->belongsTo('Category', 'category_id');
    }
   
   public function material(){
        return $this->belongsTo('Material', 'material_id');
    }
 }
`
you can apply the same thing to DataEdit

**Comment by serverfire** [comment]
@vijaybonzer  i hope you did get help you need .
Please ask any other questions you have .
Thank you
