### ISSUE TITLE
Unable to see the login page

### ISSUE THREAD

**Issue by sonusindhu** [serverfireteam/panel#104]
Hello Team,

I have installed the panel and using laravel 5.0. All the steps has been completed successfully but once I am trying to open the example.com/panel it redirect me to example.com/panel/login with the blank page.
Let me know if I need to update or do anything else to run this.

Thanks for your help.

Regards,
Sonu

**Comment by serverfire** [comment]
@sonusindhu I do suggest to use last laravel 5.1 and use last laravel panel version .

If you still have this problems , send us the composer.json , composer.lock and your debug logs 


Thank you for using the laravel panel , keep in mind we will be very happy if you can help us with Hindi translate .

Thank you

**Comment by sonusindhu** [comment]
Thanks for your reply.
Please send me email so I can forward all the file to test like composer.json etc
Regards,
Sonu

**Comment by serverfire** [comment]
@sonusindhu  you can just send this files to info@serverfire.net
