### ISSUE TITLE
panel based on logged in user

### ISSUE THREAD

**Issue by wyklif** [serverfireteam/panel#107]
Hello, this is just a question say i have a website where i have many users can i have a panel based on the logged in user?

**Comment by serverfire** [comment]
@wyklif  Yes you can have that , install from user_roles_5 branch

**Comment by wyklif** [comment]
That is great!! could you point me to documentation of the user roles and will this package serve the same purpose as https://github.com/FrozenNode/Laravel-Administrator 


     On Saturday, September 19, 2015 8:57 AM, Serverfire <notifications@github.com> wrote:
   

 @wyklif Yes you can have that , install from user_roles_5 branch —

**Comment by serverfire** [comment]
@wy Right now the user roll is in alpha stage and we don't have any document , 
 we have way more features than frozenNode .
