### ISSUE TITLE
Add an example of how to use a <select> dropdown in for searching/filtering

### ISSUE THREAD

**Issue by pwlife** [serverfireteam/panel#108]
One suggestion -- 

It might be a useful to add an example to the FAQ of how to filter/search through a table using a <select> dropdown with an blank first option.   

The current example in the FAQ causes a problem with searching -- eg: it will search on the field, even though the field is "blank".

For searching, you have to do something like this:

```
$options = Department::lists("name", "id")->all();
//you must explicitly declare that the first option is an empty key-value pair!
$empty_option = array(""=>"Select a Department");
$department_options= $empty_option + $options;
$this->filter->add('parent_id', 'Department', 'select')->options($options);
```

This will produce HTML like this:
```
<select>
<option selected>Select a Department</option>
<option value="1">Accounting<option>
<option value="2">Human Resources</option>
<option value="3">Engineering</option>
</select>
```

Thanks!

**Comment by pwlife** [comment]
Nevermind, I figured it out.  Adding this answer in case anyone else Googles and finds it.

In the FAQ, it states that the way to add an empty option to a <select> is like this:

```
//  how to add a <select>   to the search fields
$options = Department::lists("name", "id")->all();
array_unshift($options, "'');
$this->filter->add('parent_id', 'Department', 'select')->options($options);
```

This will produce HTML like this:
```
<select>
<option value="0"></option>
<option value="1">Accounting<option>
<option value="2">Human Resources</option>
<option value="3">Engineering</option>
</select>
```

Notice that the empty option got assigned a value of "0". Therefore, if the <select> box is set to empty, and you search, the server will try to find all entries in the Department table with id=0.  This is not what I wanted...I didn't want anything to be searched if <select> was empty.

Instead, you can add empty fields like this:

```
$options = Department::lists("name", "id")->all();
$empty_option = array(""=>"");
$department_options= $empty_option + $options;
$this->filter->add('parent_id', 'Department', 'select')->options($options);
```


This will produce the correct HTML:
```
<select>
<option selected></option>
<option value="1">Accounting<option>
<option value="2">Human Resources</option>
<option value="3">Engineering</option>
</select>
```

**Comment by serverfire** [comment]
@pwlife  Thank you for your suggestion , we are going to add this , you can edit here : https://github.com/laravelpanel/docs

@alenoosh  please add this to doc , thank you
