### ISSUE TITLE
Error on demo when upload

### ISSUE THREAD

**Issue by wyklif** [serverfireteam/panel#109]
on the demo site when you try to upload pics when creating a page from the editor it gives an error ReflectionException in Container.php line 736: Class replace-this-with-your-middleware does not exist

**Comment by alenoosh** [comment]
@wyklif The configuration of elfinder was missing on demo, I have added the configuration. I have also fixed a bug related to loading files in elfinder so please update to the latest release. Thank you for reporting the problem.
