### ISSUE TITLE
i have been follow the intruction on http://laravelpanel.com/docs/master/automatic-installation

### ISSUE THREAD

**Issue by Lamhot** [serverfireteam/panel#112]
http://laravelpanel.com/docs/master/automatic-installation

but after, i write this:
php artisan panel:install

result:
[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'Serverfireteam\Panel\PanelServiceProvider' not found

**Comment by serverfire** [comment]
@Lamhot  I think you have forget to add laravelpanel to composer and install it
