### ISSUE TITLE
Model Relationship

### ISSUE THREAD

**Issue by Kelmitt** [serverfireteam/panel#113]
Hi, im using L5.1
i have table users and table donations.
table donations have usid <=> id table users (no foreing key)

i need to show the sum of donations by users. how I do this?

**Comment by serverfire** [comment]
@Kelmitt  you should read this questions ( Q: How can I display/edit data which is fetched from more than one table in CRUD ? )

here : http://laravelpanel.com/docs/master/faq

**Comment by Kelmitt** [comment]
@serverfire I first read the documentation but get error, that i opened this.

in my model User.php =  $grid = \DataGrid::source(User::with('donation'));

Error: Class 'App\Models\User' not found

The URL is where User.php

**Comment by serverfire** [comment]
@Kelmitt  please past here full code of your user model and controller

**Comment by Kelmitt** [comment]
User.php

namespace App\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

$grid = \DataGrid::source(User::with('donation'));

class User extends Model implements AuthenticatableContract, CanResetPasswordContract
{
    use Authenticatable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password', 'pseudo', 'facebook_token', 'google_token', 'twitter_token', 'status' ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token', 'facebook_token', 'google_token', 'twitter_token' ];

    public function donation() {
        return DB::table('users as a')
                      ->select(
                         DB::raw('count(yt_b.id) as donado')
                        )
                      ->leftjoin('users_donation_transactions as b', 'a.id', '=', 'b.usid')
                      ->get();
    }

}

UserController.php

public function all($entity){
        parent::all($entity); 

            $this->filter = \DataFilter::source(new \App\Models\User());
            $this->filter->add('id', 'ID', 'text');
            $this->filter->add('pseudo', 'Name', 'text');
            $this->filter->submit('search');
            $this->filter->reset('reset');
            $this->filter->build();

            $this->grid = \DataGrid::source($this->filter);
            //$grid = DataGrid::source(User::with('donation'));
            echo '<pre>';print_r($this->grid); die;
            $this->grid->add('id', 'ID', true);
            $this->grid->add('pseudo', 'Name');
            $this->grid->add('status', 'Status');
            
            $this->grid->add('defLang', 'Language');
            $this->grid->add('created_at', 'Creation Date', 'date');
            $this->addStylesToGrid();

        
                 
        return $this->returnView();
    }

its is ok?

**Comment by serverfire** [comment]
@Kelmitt 


```
$grid = \DataGrid::source(User::with('donation'));
```
 should not be in model file  , remove it 

you need change this line in controller : 
```
$this->filter = \DataFilter::source(new \App\Models\User());
```
to 
```
$this->filter = \DataFilter::source(User::with('donation'));
```

**Comment by Kelmitt** [comment]
@serverfire 

Also try this but I get this other error.

Error: Class 'App\User' not found.

because I have all models in folder "Models".

**Comment by serverfire** [comment]
add this to first of controller 
```
use App\Models\User;
```

**Comment by Kelmitt** [comment]
Well, I do not get more errors laravel panel. I think now is the model.

Call to a member function addEagerConstraints() on a non-object

**Comment by serverfire** [comment]
There is problem in your model code , take look at : 

http://stackoverflow.com/questions/20494423/call-to-a-member-function-addeagerconstraints-on-a-non-object

http://stackoverflow.com/questions/20109047/laravel-4-eager-loading

**Comment by Kelmitt** [comment]
Yep. I change to 

return $this->hasMany('App\Models\UsersDonationTransactions', 'usid', 'id');
 But now as I show the sum of donations in the grid?

**Comment by serverfire** [comment]
I think this should work , let me know 
```
$this->grid->add('{{ $donation->count }}', 'donation count');
```

**Comment by Kelmitt** [comment]
shows {{ $donation->count }} in the page.

**Comment by serverfire** [comment]
That happen when can not found Relationship , do you have record for donation ?

**Comment by Kelmitt** [comment]
yep i have 3 users and 3 records in donation.
and de column user_paid in UsersDonationTransactions need to sum.

**Comment by serverfire** [comment]
sorry test this 
```
$this->grid->add('{{ $donation->count() }}', 'donation ');
```

also try to show one of donation table field 

```
$this->grid->add('{{ $donation->field_name_here }}', 'donation field ');

```

**Comment by Kelmitt** [comment]
This work great. Tnx.
$this->grid->add('{{ $donation->count() }}', 'donation ');

This works and is the one I need
 $this->grid->add('{{ $donation->sum("user_paid") }}', 'donation field ');

but if I need to show a field 
$this->grid->add('{{ $donation->id }}', 'donation id ');

shows {{ $donation->id }} in the page.

**Comment by Kelmitt** [comment]
but if I need to show a field 
$this->grid->add('{{ $donation->id }}', 'donation id ');

shows {{ $donation->id }} in the page.

This does not work because i have relationship "hasMany", with "hasOne", i can show the fields.

Tnx @serverfire for your help.

**Comment by serverfire** [comment]
@Kelmitt  happy to help

**Comment by fahreza007** [comment]
Thank this very helpul.

But i cant show on pages.blade.php, how to show this? can you help me.
