### ISSUE TITLE
No output.

### ISSUE THREAD

**Issue by moderith** [serverfireteam/panel#115]
I'm new to Laravel, so please excuse any ignorince on my part. I installed Panel, and was able to run:

php artisan panel:crud headers

It made the model file and the controller file, but when I go to the panel admin and click the headers button nothing shows up besides export to excel or import data buttons. The link has a number beside it showing the rows in the table, and when I export data the rows appear in the file.

What am I doing wrong?

**Comment by MehmetOzkose** [comment]
customize your crud file for your needs. My categoriesController just like that:

class categoriesController extends CrudController{

    public function all($entity){
        parent::all($entity); 

			$this->filter = \DataFilter::source(new \App\Categories);//your model e.g:Headers
			$this->filter->add('name', 'Name', 'text');
			$this->filter->submit('search');
			$this->filter->reset('reset');
			$this->filter->build();

			$this->grid = \DataGrid::source($this->filter);
            $this->grid->add('id','ID', true)->style("width:100px");//id,name mysql field names
            $this->grid->add('name','Category Name');


            
			$this->addStylesToGrid();
                
        return $this->returnView();
    }

**Comment by moderith** [comment]
@MehmetOzkose Thanks! That's what I was missing.

**Comment by serverfire** [comment]
@MehmetOzkose  Thank you for helping out

**Comment by MehmetOzkose** [comment]
@serverfire @moderith You're welcome
