### ISSUE TITLE
S3 uploads.

### ISSUE THREAD

**Issue by moderith** [serverfireteam/panel#116]
Is it possible to upload files/images to S3 instead of the local file system?

**Comment by alenoosh** [comment]
@moderith Yes it is possible. Just set your default filesystem to 's3' and set your credentials and also change configuration of elfinder as the following : 

````
'disks' => 's3',
.
.
'roots' => null,
```

**Comment by moderith** [comment]
@alenoosh Thanks for the help.

I followed these steps, but my files just upload locally as they did before. I was able to successfully upload files to S3 with the Storage facade using:

    Storage::put('website/files/test.txt', 'hello world');

In my controller edit function I'm using:

    $this->edit->add('social-image', 'Share Image (1200x630)', 'image')->move('website/files/')->preview(120,63);

Thanks again!

**Comment by alenoosh** [comment]
@moderith Well right now it is not possible to upload images to S3 buckets by adding a field in the panel.
It's just possible to use it by 'upload image' button in the text editor of our panel. But we'll work on it in the future and we will inform you as soon as it's released.
