### ISSUE TITLE
1.2.* with Laravel 5.0 problem

### ISSUE THREAD

**Issue by Briganti** [serverfireteam/panel#118]
Hi, I've made a fresh install of version 1.2.* on Laravel 5.0 but something goes wrong, check my screenshot:
![laravel-panel](https://cloud.githubusercontent.com/assets/4698649/10264456/88f3a474-6a14-11e5-98a4-69ad435f4845.png)
There is some design issues on the top right corner, an some assets files are missing.
I've added the "zofe/rapyd": "2.0.*" to the composer.json but this doesn't resolved my problem, the 2.0.* version of rapyd-laravel doesn't contains the redactor files.

(Sorry for my english)

**Comment by serverfire** [comment]
@Briganti this are problems we solve in 1.3.* , you should upgrade to laravel 5.1 and use 1.3.*

**Comment by Briganti** [comment]
I'm limited by the PHP version, the Laravel 5.1 requires PHP >= 5.5.9 and I have only 5.5.4 on the shared host where my site will be installed :(

**Comment by Briganti** [comment]
I've fixed the layout problems, how can I send to you to review and make a new tag with it to be available on composers updates?

(Sorry, I'm familiar only with subversion)

**Comment by serverfire** [comment]
@Briganti thank you for you fix , i have merge your code to 1.2.12 , branch laravel5
