### ISSUE TITLE
Edit relationship and export to prod

### ISSUE THREAD

**Issue by Reykon** [serverfireteam/panel#120]
Hi, im using L5.1
i have table users and users_profile
table users_profile have usid <=> id table users

i try this:

my model User

public function profile() {
        return $this->hasOne('App\UsersProfile', 'usid', 'id');
 }

my userscontroller

public function  edit($entity){
        
        parent::edit($entity);

        $this->edit = \DataEdit::source(User::with('profile'));

        $this->edit->label('Edit User');

        $this->edit->add('name', 'Name', 'text');
       
        return $this->returnEditView();
    }    

got this error:
FatalErrorException in DataEdit.php line 81: 
Class name must be a valid object or a string.

I need to show profile field and then you can edit. How stored in two tables?

The other question is: When finish  the panel in dev, how i export to prod?

tnx for ur help

**Comment by Reykon** [comment]
any help please?

**Comment by serverfire** [comment]
@Reykon  
I think you got that error because DataEdit can not access to model , check your namespace of model.

Right now curd save data in just one table if you want save to more than one table you have to listen to model event like insert  and insert you record in second table .

If you want to upload in host or server just uploads all files and disable the debug and remove link curd from your admin .

**Comment by Reykon** [comment]
@serverfire 
I think you got that error because DataEdit can not access to model , check your namespace of model.

This work
$this->edit = \DataEdit::source(new User());
then I think that if you have access to model.

and this also works when I try to show
$this->filter = \DataFilter::source(User::with('profile'));

**Comment by Kelmitt** [comment]
i have the same problem :/

**Comment by Kelycon** [comment]
Hi.
one to solve it?
I have the same error.

Can anyone help me?

**Comment by alenoosh** [comment]
@Reykon @Kelmitt @Kelycon In order to make relations work for DataEdit you should specify the relation in fieldname of 'add' method : 

````
     $this->edit = \DataEdit::source(new \App\ModelName());
     $this->edit->add('relation.fieldname', 'Field Label', 'text');
````

**Comment by MehmetOzkose** [comment]
Maybe this helps

https://github.com/serverfireteam/panel/issues/106

**Comment by alenoosh** [comment]
@MehmetOzkose No, the problem here is that they want to save data into two related tables. But anyway thanks for your comment.

**Comment by Kelmitt** [comment]
@alenoosh 
tnx, this work.

About save date in two tables. 

@serverfire said to liste the event like insert. 

\App\Modelname::creating(function($data) {
        $data->password = Hash::make(\Request::input('password'));
 });

Here I should insert into another table??

**Comment by serverfire** [comment]
@Kelmitt  i was wrong , you don't need that 
What alenoosh said will save in both table

**Comment by Kelmitt** [comment]
@serverfire I missed a bit.

It will save data into two related table automatically?

**Comment by Kelmitt** [comment]
wowww i test it, work fine. tnx for ur help. its is awesome.

**Comment by serverfire** [comment]
@Kelmitt  we would be happy if you translate it to your native language .
Thank you in advance

**Comment by Kelmitt** [comment]
@serverfire sorry, I do not understand what do you want

**Comment by serverfire** [comment]
I mean we need translate the package to many language as possible , could you helping us with that ?

**Comment by Kelmitt** [comment]
Ohh ok, but I can not, I'm sorry, work all day and do not have much time left.
