### ISSUE TITLE
Model relationship in the same table

### ISSUE THREAD

**Issue by MehmetOzkose** [serverfireteam/panel#125]
Hi!
I have a table named categories as you know  :) This table is related to itself by parent_id.

id | name | parent_id
------------ | -------------  | -------------
1 | cat1 | 0
2 | cat2 | 1
3 | cat3 | 1

I want my greed seem to be like this:

id | name | parent category name
------------ | -------------  | -------------
1 | cat1 | no parent category
2 | cat2 | cat1
3 | cat3 | cat1

I tried something like that but no result:
` return $this->belongsTo('App\Categories', 'name as parentName','id','parent_id'); `

` $this->grid->add(' {{@$categories->parentName}}','parent category name'); `

Thanks.

**Comment by MehmetOzkose** [comment]
Solved by this way, maybe helpful for someone:

categories model:

    public function mother() {
        $mother = $this->belongsTo('App\Categories','parent_id');
        if(isset($mother->kids)) {
            $mother->kids->merge($mother);
        }
        return $mother;
    }

and controller:

 $this->grid->add(' {{@$mother->name}}','Parent Category');

http://neonos.net/laravel-eloquent-model-parentchild-relationship-with-itself/

**Comment by alenoosh** [comment]
@MehmetOzkose Thanks alot for sharing your information, this will be really helpful to others.
