### ISSUE TITLE
Concatenate URL with data of relatioship

### ISSUE THREAD

**Issue by Kelycon** [serverfireteam/panel#126]
to access an image, the route depends on the user id.

$this->edit->add('profile.bannerImg', 'Banner', 'image')->move('media/users/')->preview(80,80); 

BannerImg contains only a hash, lack extension (.jpg) and the route of images is media/users/profile.user_id.
(yep is a relation)
How to concatenate the url it is correctly formed?

@serverfire  @alenoosh

**Comment by Kelycon** [comment]
any help please?

**Comment by serverfire** [comment]
@Kelycon 
Sorry for late replay , we had busy week .

only problem you have is image save without extension ?

```
$this->edit->add('profile.bannerImg', 'Banner', 'image')->move('media/users/')->preview(80,80)->rule('mimes:jpeg');
```

Try this one .

Also you don't need extension for you images files  .

Image files have header that content type of image so when you link them it would work in browsers , also you can create route in laravel to have extension for image like this : 

```
Route::get('get_image/{hash}.jpg', function(){
// return image content 
});
```

**Comment by Kelycon** [comment]
@serverfire 
Thank you for reply.
the route of images is media/users/{profile.user_id}.

example "media/users/1/logo/logo.jpg"

How to concatenate the url it is correctly formed?

i try:
$this->edit->add('profile.bannerImg', 'Banner', 'image')->move('media/users/profile.user_id')->preview(80,80); 
but just show me the text and no the id.

**Comment by Kelycon** [comment]
@Globax you make  a multilenguage form.
this https://github.com/serverfireteam/panel/issues/63
Can you help me to make the same?
