### ISSUE TITLE
Show HTML link and plain text in edit interface

### ISSUE THREAD

**Issue by Kelmitt** [serverfireteam/panel#127]
How I can show html link on the edit form ?
something like this:

final result like:
Social:     FacebookLink

code maybe? that dont work.
$this->edit->add('< a h ref="https://www.facebook.com/{profil.facebook_user}">Facebook</ a>', 'Social', '');

understand?

also plain text like this:
Last Update :    2015-17-10
Not input text or date, just plain text.

**Comment by siavash13** [comment]
This is actually a Form and it is supposed to get some data from the user, and you can add elements to your form which are defined in HTML specs so could you please provide us an example that shows why should we need a social link inside a form?
