### ISSUE TITLE
controller subfolder admin

### ISSUE THREAD

**Issue by thedangler** [serverfireteam/panel#128]
I want to separate out my admin controllers.
I have a subfolder called admin
using the createcontroller i was able to make them in the correct spot but your links is to simple and doesn let you specify the controller location.

**Comment by thedangler** [comment]
I ended up editing the mainController

**Comment by siavash13** [comment]
you could have set a variable inside your `panel.php` file inside your config folder of you app then, name it `controllers` and point it to the directory where you need controllers to be loaded from
