### ISSUE TITLE
Setup in windows

### ISSUE THREAD

**Issue by Drmzindec** [serverfireteam/panel#130]
Tried setting this up in Windows 10 with Laravel 5.1 and WAMP. The setup goes fine but step 3 returns a 404 error.

3. Go to your domain.com/panel and you can login with the following username and password : user : admin@change.me password : 12345

1. DB setup went fine
2. File setup went fine

Panel almost doesn't seem to exist after instillation.

**Comment by serverfire** [comment]
@Drmzindec are the domain.com work ? do you see laravel 5.1 home page ?

**Comment by Drmzindec** [comment]
I see Laravel homepage but the panel doesn't work.

The domain.com does work.

**Comment by serverfire** [comment]
@Drmzindec  check if you have put Serverfireteam\Panel\PanelServiceProvider::class in config/app.php providers ?
