### ISSUE TITLE
ProviderNotRegisterdException after installing

### ISSUE THREAD

**Issue by mstroeck** [serverfireteam/panel#133]
Hi,

When following the install instructions exactly on Laravel 5.1, I am getting the following error when trying to access the panel:

ProviderNotRegisteredException in ProviderRegistry.php line 17:
No provider has been registered under the alias 'panel'

Any ideas?

**Comment by serverfire** [comment]
@mstroeck 
Sorry for late replay 
Are you sure you have serverfireteam/panel in vendor folder ?
