### ISSUE TITLE
Data import documentation 

### ISSUE THREAD

**Issue by jamespsterling** [serverfireteam/panel#134]
Documentation on how the import works and what's required for successful import would be useful.

This is what I get if I try to upload a CSV in the same format as my table,
```
Data import failed, please check the validation of data.
```

**Comment by serverfire** [comment]
@jamespsterling try this , export from panel and open the files and reupload it and it will import , you should have same format as exported version .

**Comment by jamespsterling** [comment]
I tried this with no luck. I exported a single entry from one of my models/pages and then filled it with data. I then get the error message above. Any idea how to debug without digging deep into the code?

**Comment by alenoosh** [comment]
@jamespsterling This error occurs just in case the value of one of 'not null' fields is empty/null. Please check your values and let me know if this error occurs again.

**Comment by jamespsterling** [comment]
Yeah, that worked like a charm. Thanks!
