### ISSUE TITLE
Class 'App\Role' not found on export to excel

### ISSUE THREAD

**Issue by jamespsterling** [serverfireteam/panel#135]
Export to excel is throwing n error on the ```user_roles``` branch. Looks like it's having trouble figuring out the namespace for the Roles model. 

The following returns ```App\Role```, when I'm thinking it should return ```Serverfireteam\Panel\Role```
```
	$className = $appHelper->getNameSpace() . $entity;
```

Stack trace ref:
```
FatalErrorException in ExportImportController.php line 16:
Class 'App\Role' not found
```

**Comment by alenoosh** [comment]
@jamespsterling We are going to rewrite the 'user management' in the near future so this branch will be deleted and the bugs will be fixed.
