### ISSUE TITLE
[Blocker] Migrations issue

### ISSUE THREAD

**Issue by xcopy** [serverfireteam/panel#14]
When I run `php artisan migrate:reset` I can see

```
[Illuminate\Database\QueryException]                                                                 
SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'links' (SQL: drop table `links`) 
```

```
[PDOException]                                                             
SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'links'
```

Looks like issue is in `src/database/migrations/2015_03_15_123956_edit_url_table.php`:

Look at `down` method

```
public function down()
{	
    Schema::drop('links');
}
```

It's already drops the `links` table. But there is one more drop - in `src/database/migrations/2015_02_20_130902_create_url_table.php` and thats why there is `Unknown table 'links'`

**Comment by serverfire** [comment]
@xcopy  thank you , it is fixed in master branch .
@alenoosh will release new version soon .
@alenoosh  please after test , close this issues and #9
