### ISSUE TITLE
Repeatable child entities

### ISSUE THREAD

**Issue by jamespsterling** [serverfireteam/panel#141]
I have a one-to-many relationship where I'd like to allow entry on the child entity (with many fields) one or more times. Is this possible with laravelpanel?

**Comment by serverfire** [comment]
@jamespsterling one -to -many relationship  with same model or with two model ?

**Comment by jamespsterling** [comment]
Multiple models. Example, I have a table that tracks submissions and that table references a child table that has repeatable entries/rows.

Example of visual repeating blocks (entry rows),
![image](https://cloud.githubusercontent.com/assets/6403652/11191163/68b5d7fa-8c5f-11e5-9134-a79f2ab573ec.png)

**Comment by serverfire** [comment]
@jamespsterling you can  create other crud for child entity

**Comment by jamespsterling** [comment]
How would that child entity know with parent it belongs to?

**Comment by serverfire** [comment]
@jamespsterling  a select box with parent list and ids

**Comment by jamespsterling** [comment]
That's not very intuitive for the user eh?

**Comment by serverfire** [comment]
@jamespsterling  we have in mind to create some good ui for that , as we have limited budget right now would be good use some help on that , we just need open child crud in bootstrap modal and when they after select child so users can create child in same page

**Comment by jamespsterling** [comment]
Gotcha. A modal isn't a bad idea. I might be able to work something up like that. I'll submit a pull request if I get that far.

**Comment by serverfire** [comment]
@jamespsterling  
That would be great if you do that , 
we need to have both crud we just need to load the child one in modal and add link to after select box , for that you need copy & past the https://github.com/serverfireteam/rapyd-laravel/blob/master/src/DataForm/Field/Select.php and change it to something like deep select with button after that , open a modal with ifram to child crud , after modal close refrash the select-box .

**Comment by mxmtsk** [comment]
@jamespsterling did you get that working or what is the status with that? :)

**Comment by jamespsterling** [comment]
@mxmtsk I implemented this with ng-admin / REST instead. 

https://github.com/marmelab/ng-admin

**Comment by serverfire** [comment]
@jamespsterling do not advertise other package here

**Comment by jamespsterling** [comment]
@mxmtsk I decided to go a different direction with the solution.
