### ISSUE TITLE
Route to custom controller / view

### ISSUE THREAD

**Issue by thedangler** [serverfireteam/panel#142]
What should the route be for the custom controller also how do you add a link to that it seems like the links on the left only match up with models.
You guys need to be a little more detailed in the documentation.

**Comment by alenoosh** [comment]
@thedangler You should add your custom route in the 'app/http/route.php' file of your app, for example : 

````
Route::get('/panel/YourEntity/CustomAction/{id}', 'CustomController@action');
````

Yes you are right, the links on the menu (left sidebar of panel) are added via each model. If you need to add link to your custom controller, you can edit the 'resources/views/vendor/panelViews/mainTemplate.blade.php'. We will work on this feature in the future.

We will try our best to add detailed info in our documentation, thanks alot for sharing your idea about this.
