### ISSUE TITLE
Checkbox input form shown not selected

### ISSUE THREAD

**Issue by jedidas** [serverfireteam/panel#144]
Hello, sorry for my bad English, in my project with 5.1 laravel used laravel panel, is an incredible tool thanks, but I have a problem.
I have a boolean value in my table (migration). Example
```php
$table->boolean('state')->default(true);
```
And in my controller in the function edit field type checkbox. Example
```php
$this->edit->add('state', 'Visibilidad', 'checkbox');
```
My problem is this, when I edit the value of the checkbox input form shown not selected, regardless of its value.
How I can mark the input as checked if its value is true?
Thank you very much for your help

**Comment by serverfire** [comment]
@jedidas  as we are using rapyd-laravel and in document it say "checkbox, usually used to work with a boolean 0-1 value, but it can be configured on different values (to be usable also for enum fields)"

Change that to 0-1 and see it work or not and let me know

**Comment by jedidas** [comment]
Hello, change the checkbox for radiogroup and it worked.
```
$this->edit->add('state', 'Visibilidad', 'radiogroup')->option('Invisible', 'Invisible')->option('Visible', 'Visibilidad');
```

Thank you
