### ISSUE TITLE
I'm working crud appliction in modules I've followed your instructions but it's showing this error Exception in CrudController.php line 70: This url is not set yet!

### ISSUE THREAD

**Issue by tayyabkhanrind** [serverfireteam/panel#145]
I'm working crud appliction in modules I've followed your instructions but it's showing this error Exception in CrudController.php line 70: This url is not set yet!

**Comment by siavash13** [comment]
based on the error you provided it seems that package is not installed properly and configs are not published correctly please execute this command in the command line in the root of your project : 
`php artisan panel:install`

and please let me know when you say it says that `CrudController.php line 70: This url is not set yet!` which url you are trying to visit in the address bar that exactly

**Comment by tayyabkhanrind** [comment]
It's working when i'm not using modules. When I use modules it show error as shown above Exception in CrudController.php line 70: This url is not set yet!
![inv-directory-structure](https://cloud.githubusercontent.com/assets/4836636/11522990/9d6f26b8-98df-11e5-8d63-5d571d60ff22.png)

**Comment by serverfire** [comment]
@tayyabkhanrind you have to put the controller info in link table
