### ISSUE TITLE
Custom link in the Grid?

### ISSUE THREAD

**Issue by jedidas** [serverfireteam/panel#146]
Hello, as you might add a custom link to the grid, as is done in rapyd-laravel?
Example by rapyd-laravel
```
$grid->link('/articles/edit',"Add New", "TR");  //add button
```
Try using this example but no link is not displayed.
Please help

**Comment by serverfire** [comment]
@alenoosh  could you take look at this one?

**Comment by alenoosh** [comment]
@jedidas You can use the the grid 'add' method to add html tags directly like the following example : 

````
	$customUrl = url('/panel/customAction/all?id={{ $id }}');
	$this->grid->add('<a href="' . $customUrl . '">Custom Action</a>', '');
````

This will add a link in your grid (for each row in grid).

Please let me know if this solves your problem.

**Comment by jedidas** [comment]
The solution works perfectly.
Thank you very much for your support, laravelpanel is incredible.
