### ISSUE TITLE
How to create dynamic dropdowns, date between filter, and how can we change listing query filter?

### ISSUE THREAD

**Issue by tayyabkhanrind** [serverfireteam/panel#147]

**Comment by siavash13** [comment]
for creating a dynamic dropdown, let's say you have `Product` and `Category` models 
in `ProductController` add 
`        $this->edit->add('category_id', 'Category', 'select')->options(\App\Category::lists('name', 'id')->all());`

and easily a dropdown will be added to your `edit form` 

about date between filter and listing query filter could you please make it more clear?

**Comment by tayyabkhanrind** [comment]
thanks for help
About Date between filter let me explain with an example
suppose we have orders grid and i want to search orders placed between 22 Nov 2015 and 28 Nov 2015 how i can make these fields and how i can make search accordingly?

**Comment by siavash13** [comment]
so far nothing like your requirements has been implemented yet in the package, so either you can add it to the package and you'll be credited for this contribution or you can just implement it for your own project

**Comment by tayyabkhanrind** [comment]
I wish but I've not worked on any package yet. If some one guide me I can do it

**Comment by serverfire** [comment]
@tayyabkhanrind  you can just edit in your vendor , serverfireteam/rapyd-laravel package , look for filter functions there after that push the code to https://github.com/serverfireteam

**Comment by dm00z** [comment]
I tried 
`$this->edit->add('category_id','Category','select')->options(\App\categories::lists("category_name", "id")->all());` 
in my `productController`, but I got `Call to a member function all() on array`.

Is there any additional step to make it works?

**Comment by tayyabkhanrind** [comment]
It's working at my side
$this->edit->add('category_id', 'Category', 'select')->option('', 'Select Category')->options(Category::lists("name", "id")->all());
Check your model path or copy code in more details

**Comment by dm00z** [comment]
@tayyabkhanrind Well, it works when I tried
`$this->edit->add('category_id','Category','select')->options(\App\categories::lists("category_name", "id"));`
