### ISSUE TITLE
run command

### ISSUE THREAD

**Issue by davidbuenonnoleto** [serverfireteam/panel#149]
when I run the command:

php artisan panel:install

I got this problem:
                                                   
  [PDOException]                                    
  SQLSTATE[HY000] [2002] No such file or directory

**Comment by serverfire** [comment]
@davidbuenonnoleto  I would say that you have a problem connecting from PHP to MySQL...

http://stackoverflow.com/questions/2412009/starting-with-zend-tutorial-zend-db-adapter-throws-exception-sqlstatehy000

http://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory
