### ISSUE TITLE
Error on CMD Class Serverfireteam\Panel\PanelServiceProvider Not found

### ISSUE THREAD

**Issue by kantsverma** [serverfireteam/panel#151]
All steps work fine for me in i have update the composer then add the provider to config/app.php. But its give me error when i try to install the panel. I think i am missing something or not configuring properly can you please guide me about this. 
I have attached the chages of composer, app and CMD output. Please check it in attached document. 

Kind Regrads
Kantsverma 
![cmd](https://cloud.githubusercontent.com/assets/6929043/12008092/9b43f646-ac4b-11e5-8e71-149afe1ead20.PNG)

![app php-changes](https://cloud.githubusercontent.com/assets/6929043/12008087/4b9439d0-ac4b-11e5-8f8d-d9c23dfb8abb.PNG)
![composer-changes](https://cloud.githubusercontent.com/assets/6929043/12008088/50662612-ac4b-11e5-8a31-923942514306.PNG)

**Comment by serverfire** [comment]
Check your vendor folder to see if you have the serverfireteam/panel ,

**Comment by kantsverma** [comment]
There is no directory like serverfireteam/panel in vendor folder. How can i integrate this panel manually ?

**Comment by serverfire** [comment]
This mean you did not install laravelpanel at all , check your
composer.json to see if it have laravelpanel in require and do a composer
update

On Sun, Dec 27, 2015 at 5:46 PM, Kantsverma <notifications@github.com>
wrote:

> There is no directory like serverfireteam/panel in vendor folder. How can
> i integrate this panel manually ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serverfireteam/panel/issues/151#issuecomment-167416970>
> .
>



-- 
Best regards
Alireza Aboutalebi
Serverfire.net

**Comment by kantsverma** [comment]
I follow the steps that you mentioned 
I have install laravel using composer
Then update the composer.json in root of projects 
Then update composer 
Then  make changes in config/app/php
Then try last php artisan panel:install
But it show the same message

**Comment by serverfire** [comment]
Read this page : http://laravelpanel.com/docs/master/automatic-installation
and add laravelpanel to composer and update it .

Where you read that steps ?

On Sun, Dec 27, 2015 at 6:00 PM, Kantsverma <notifications@github.com>
wrote:

> I follow the steps that you mentioned
> I have install laravel using composer
> Then update the composer.json in root of projects
> Then update composer
> Then make changes in config/app/php
> Then try last php artisan panel:install
> But it show the same message
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serverfireteam/panel/issues/151#issuecomment-167417945>
> .
>



-- 
Best regards
Alireza Aboutalebi
Serverfire.net

**Comment by kantsverma** [comment]
I was following steps from here : https://github.com/serverfireteam/panel
But i follow the steps from New URL that you send me recently. Now i get a new error please check it in attached CMD screenshorts
![new-error](https://cloud.githubusercontent.com/assets/6929043/12010725/5258f30e-acd8-11e5-81b1-97339daebb50.PNG)

**Comment by serverfire** [comment]
you have to install fileinfo 
which version of laravel you have installed , if it is 5.1 you need install laravelpanel 1.3.* not 1.2.*

**Comment by kantsverma** [comment]
Laravel version is 5.o
you can see in composer 
"require": {
		"laravel/framework": "5.0.*",
		"serverfireteam/panel": "1.2.*"
	},

**Comment by serverfire** [comment]
install the fileinfo and it should work

**Comment by serverfire** [comment]
don't forget composer update

**Comment by kantsverma** [comment]
Thank you finaly i have done it i install a fresh laravel and then try this it works now when i login using the mentioned email it show error i think its due to there is no admin table in database. From where i can change the table names
![capture2](https://cloud.githubusercontent.com/assets/6929043/12011022/2b556f9c-ace4-11e5-86ce-66c196f12791.PNG)

**Comment by kantsverma** [comment]
How i cam extend the admin menus can i remove the Link section from admin I want to add the categories, products etc tabs and make it working can you suggest me any documentation or guide me  further to use this admin panel

**Comment by serverfire** [comment]
admin menu data come from the links table , you could edit this table records , here the document : laravelpanel.com/docs

**Comment by spsbm** [comment]
my site has"serverfireteam/panel"  vendor folder . I have installed fileinfo too.
still i get - There are no commands defined in the "panel" namespace error

**Comment by rishisain** [comment]
Hi I have installed the  Laravel 5.2.31 and after that when I execute this following command: php artisan panel:install then I got this Error message: 
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Serverfireteam\Panel\PanelServiceProvider' not found

I have followed all the instruction which you have mention this site: http://laravelpanel.com/docs/master/automatic-installation

But after that I got this message. This is my project URL: http://webdevelopcompany.com/fundmyjustice/laravel/

I have attached all the required documents. Please help me to find out any solution.
![app](https://cloud.githubusercontent.com/assets/10656078/15488094/6714c036-2170-11e6-9e6d-fd3553cbfd03.png)
![composerjson](https://cloud.githubusercontent.com/assets/10656078/15488093/6712aeea-2170-11e6-9e7e-283c448638f5.png)
![1](https://cloud.githubusercontent.com/assets/10656078/15488095/6716ce76-2170-11e6-8ca0-e0ea71381e3e.png)

**Comment by luannguyenQV** [comment]
@rishisain you must: composer update // I make same error, and soved.
