### ISSUE TITLE
Error on deleting some existing models and their controllers.

### ISSUE THREAD

**Issue by hassansaqib** [serverfireteam/panel#152]
Hi, I am deleting some models and their controllers. The following error is encountering.
FatalErrorException in dashboard.php line 31:

Further, I have created the model using crud command. i.e. php artisan panel:crud Test and on deletion the above error encountered. What should I do to fix it?

**Comment by serverfire** [comment]
@hassansaqib After removing a controller you have to remove the record from db from links table

**Comment by luckysong** [comment]
How? Can you help elaborate on how to delete the record from db?

**Comment by serverfire** [comment]
@luckysong with phpmyadmin or something , you have removed the controller by hand so remove the record by hand too
