### ISSUE TITLE
laravel 5.2?

### ISSUE THREAD

**Issue by Geeknux** [serverfireteam/panel#155]
HI, do you have any plan to support laravel 5.2 soon?
because there is some problem with deprecation in laravel 5.2

**Comment by serverfire** [comment]
@Geeknux  i don't think would be hard to support , Could you fork , edit the composer json for "illuminate/support": "~5.2",  and test it out and send pull request ?

**Comment by serverfire** [comment]
Right now with laravel 5.2 we get this error on panel installation : 


 [Symfony\Component\Debug\Exception\FatalErrorException]
 Call to undefined method Illuminate\Foundation\Application::bindShared()

**Comment by serverfire** [comment]
rapyd-laravel did not have working 5.2 version yet ,we have to wait for that

**Comment by thedangler** [comment]
also lluminate\Html\HtmlServiceProvider::class is gone so it wont work anyways.

**Comment by serverfire** [comment]
@thedangler we have replace it with Collective\Html and it work without problem .

**Comment by thedangler** [comment]
As of last night when I did a update for the panel it was still there.
Do I just need to replace the line of code where it looks for it?

**Comment by arafatx** [comment]
I got this error when running: php artisan vendor:publish

I followed exactly what the documentation said. Running laravel 5.2.10

 [Symfony\Component\Debug\Exception\FatalThrowableError]
  Fatal error: Class 'Illuminate\Html\HtmlServiceProvider' not found

**Comment by serverfire** [comment]
@thedangler forgot the tell you , it is in dev-master branch we did not release new version as it have little more work ,

**Comment by serverfire** [comment]
@arafatx for now you should use laravelpanel with laravel 5.1

**Comment by arafatx** [comment]
@serverfire Tried on laravel 5.1.* still got the same error message. I even added this line in the service provider:

		Collective\Html\HtmlServiceProvider::class,

any help ?

**Comment by serverfire** [comment]
@arafatx there was problem with 5.1 version and now it should get fixed, please do composer update

**Comment by arafatx** [comment]
Now I can publish the assets but, I got the following error while accessing domain.com/panel

Class 'Collective\Html\FormFacade' not found (View: E:\laragon\www\domain\resources\views\vendor\panelViews\login.blade.php)

but I after installing the laravelcollective manually, I got it working.

**Comment by lagbox** [comment]
@serverfire can the `rapyd-laravel` version be bumped >= 1.5.10?

**Comment by serverfire** [comment]
@lagbox i have change that to 1.5.8 as other version did not work with laravel 5.1 . if you send that pull request we can fix all this, thank you

**Comment by lagbox** [comment]
@serverfire on Laravel 5.1 if I use the `rapyd-laravel` 5.1.12 that problem goes away, but I am not sure if there was other reasons you weren't using the recent version

**Comment by serverfire** [comment]
@lagbox version 1.5.8 is tested version and newer version have are not tested

**Comment by lagbox** [comment]
If anyone wants to test this you just have to add a line to `composer.json` after `serverfireteam/panel`:

    ...
    "serverfireteam/panel": "1.3.*",
    "serverfireteam/rapyd-laravel" : "1.5.12 as 1.5.8"

rapyd-laravel 1.5.12 seems to be working fine for me on Laravel 5.1.28

**Comment by serverfire** [comment]
We have new version for laravel 5.2  , please test it from dev-master and let me know .

@lagbox  Thank you for great work .

**Comment by serverfire** [comment]
for laravel 5.2 need to install from serverfireteam/panel 1.4.*
