### ISSUE TITLE
Committed crud broke artisan for other developers

### ISSUE THREAD

**Issue by luckysong** [serverfireteam/panel#158]
This is happening to the developer pulls the commit with fresh new laravelpanel and a new crud.
We have two developers working on a laravel project, say A and B.

1. "Dev A" went through the tutorial and installed the laravelpanel
2. Made a new crud
3. Commit the new crud
4. "Dev B" pulled the commit
5. Fail with following error message:

 php artisan clear-compiled handling the pre-update-cmd event returned with an error

  [RuntimeException]
  Error Output: PHP Fatal error:  Class 'PHPExcel_Shared_Font' not found in /Users/B/Documents/Proj/Project/
  config/excel.php on line 174
  PHP Stack trace:
  PHP   1. {main}() /Users/B/Documents/Proj/Project/artisan:0

**Comment by serverfire** [comment]
@luckysong i do suggest your developer  check the vendor\phpoffice\phpexcel folder if he can't see the phpexcel files , it mean some how he couldn't install the laravelpanel completely .

do other composer update

**Comment by luckysong** [comment]
Thanks @serverfire. The developer tried a couple of times with composer update, but the excel font missing exception always blocks the composer to run. We have another developer also had similar issue.

**Comment by serverfire** [comment]
Remove laravelpanel from config/app.php service provider first and update
after that

**Comment by serverfire** [comment]
Send me a email to I can personally fix this problem .

Support @ Serverfire . net
