### ISSUE TITLE
Can't Login "dev-master" Laravel 5.2

### ISSUE THREAD

**Issue by kifahhk** [serverfireteam/panel#161]
Hello,
I tried to lock the dev-master version, in order to get it working on Laravel 5.2
I see the login Panel, but after giving the credentials and pressing login, It doesn't redirect to Dashboard, It just reload the login page without errors.

any Idea?

**Comment by serverfire** [comment]
@kifahhk  we are working on it , fix will be ready in a hour

**Comment by serverfire** [comment]
@kifahhk  it is fixed , do a composer update , and php artisan panel:install , don't forget to remove old panel view from resources first .

**Comment by kifahhk** [comment]
@serverfire thanks very much ^^
