### ISSUE TITLE
404 after install

### ISSUE THREAD

**Issue by SaintGiff** [serverfireteam/panel#162]
Installation went fine without errors, however when I attempt to pull up the page I'm getting a 404 from apache.  Just a generic 404.  Nothing in the apache log or the storage / log at all.  It's worth noting that the install did not change my routes.php file at all, so I'm guessing perhaps these events are related?

**Comment by serverfire** [comment]
@SaintGiff laravelpanel have it own routes.php , first please make sure you have the vendor/serverfireteam/panel and you have   Serverfireteam\Panel\PanelServiceProvider::class in config/app.php provider

**Comment by SaintGiff** [comment]
Yes, the class was absolutely added to the provider section.  However, there is not serverfireteam folder within vendors.  How on earth did that not happen during the install?

**Comment by SaintGiff** [comment]
Just did a fresh install.  The class in in the providers section, and the serverfireteam/panel directory is within vendor.  I'm still getting the 404 when attempting to hit the page.  Nothing in error logs.  Just a simple resource not found.

**Comment by serverfire** [comment]
@SaintGiff did you manage to fix this problem?

**Comment by swaylay** [comment]
@SaintGiff If you found a solution to this; please let me know what it is. I'm having the exact issue. Thanks!
