### ISSUE TITLE
Old fields in panel (from prev installation)

### ISSUE THREAD

**Issue by Hulkmaster** [serverfireteam/panel#164]
I've installed laravel+panel, made some experiments and now i've made clean install (i though so, but forgot to drop db)
and now, after clean install, creating new model + controller i have multiple fields in panel

http://take.ms/PrutC

where are these settings stored? and how to clean them?

*these fields came from prev installation

is it "links" from panel?
is the correct way to clean them - delete from panel? or i can delete them via cleaning DB directly?

**Comment by serverfire** [comment]
@Hulkmaster  they come from db table links , you can delete them with phpmyadmin or with link controller

**Comment by Hulkmaster** [comment]
ty!
i think it could be added to "faq"

**Comment by serverfire** [comment]
@Hulkmaster good idea , doing that
