### ISSUE TITLE
Tags not working

### ISSUE THREAD

**Issue by pastebimas** [serverfireteam/panel#167]
Problems while using field "tags".

ErrorException in C:\wamp\www\laravel\vendor\serverfireteam\rapyd-laravel\src\DataForm\Field\Tags.php line 171:
Undefined property: Zofe\Rapyd\DataForm\Field\Tags::$fill_tags

I have debugged, so route is really ok, the problem is, that the class "Tags" do not get the info from given json. Here is the code:

$this->edit->add('user', 'Parent', 'tags')->remote(fullname,id, route("userlist"));

I am sure, that json is ok, and it gives fullname and id.
Maybe the problem is that in serverfire/panel there is used older version of rapyd?

Thanks

**Comment by serverfire** [comment]
@pastebimas  As you can see  here : 
https://github.com/zofe/rapyd-laravel/commits/master/src/DataForm/Field/Tags.php
and here : 

https://github.com/serverfireteam/rapyd-laravel/commits/master/src/DataForm/Field/Tags.php

both have same history ,

**Comment by pastebimas** [comment]
But the problem still persists. I have even tried to use in this way:
$this->edit->add('city', 'City', 'tags')->remote("value","text", "http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/assets/cities.json");


Now it should take all the information from given json, but it still shows error: 
https://gyazo.com/3c106be1da40bf234cff8de1d8ad9ad1

Did you try it yourself?

Thank you

**Comment by serverfire** [comment]
@pastebimas it was reported bug on rapyd  , i have fix that , do a composer update
