### ISSUE TITLE
customizing controller

### ISSUE THREAD

**Issue by Hulkmaster** [serverfireteam/panel#168]
instruction on "how to make my own controller" has somethn wrong with it, or i don't get it

after completing these steps (http://laravelpanel.com/docs/master/customized-controller-view) i get error 

Exception in MainController.php line 41:
Controller does not implement the CrudController methods!

**Comment by Hulkmaster** [comment]
and if i want create custom crud controller
is there any examples how it should be done?

**Comment by serverfire** [comment]
please give us your controller and view code 

@Hulkmaster

**Comment by serverfire** [comment]
@Hulkmaster  could you tell how you want to be custom , the view ? filed type ?

**Comment by Hulkmaster** [comment]
sure

migration
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTestTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('test', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title');
            $table->string('subtitle');
            $table->string('image');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('test', function (Blueprint $table) {
            //
        });
    }
}

model
<?php 

namespace App;

use Illuminate\Database\Eloquent\Model;

class test extends Model {

    protected $table = 'test';

}


controller
<?php

namespace App\Http\Controllers;


use Serverfireteam\Panel\CrudController;

class TestController extends Controller
{
	public function all($entity)
	{

    public function __construct() { }

    public function index()
    {
        // Code

        return view('test_custom_view');
    }
	}
}


view
@extends('panelViews::mainTemplate')
@section('page-wrapper')



@stop

**Comment by Hulkmaster** [comment]
sorry for not answering for so long

**Comment by serverfire** [comment]
@Hulkmaster 

You have bug in your controller , is should be like this 

```
<?php

namespace App\Http\Controllers;

use Serverfireteam\Panel\CrudController;

class TestController extends Controller
{
	public function all($entity)
	{
		return view('test_custom_view');
	}
	public function __construct() { }

	public function index()
	{
	    // Code

	    return view('test_custom_view');
	}
	
}
```

Like that it work

**Comment by Hulkmaster** [comment]
TY! 
could you then, please, change it on the site, including namespaces? http://laravelpanel.com/docs/master/customized-controller-view

that would be great )

**Comment by serverfire** [comment]
@Hulkmaster  good idea , done
