### ISSUE TITLE
Problem with links table

### ISSUE THREAD

**Issue by robincsamuel** [serverfireteam/panel#169]
Kindly requesting you to update the table name with unique prefix. i got migration errors, since i already had a table with name 'links'.

**Comment by serverfire** [comment]
@robincsamuel we do have plan to remove links table , for know you can use other table for your links and let laravelpanel use links table , or you can fork the laravelpanel and change it

**Comment by robincsamuel** [comment]
ok thanks!

Also, I got an error while browsing to,

`/panel/Admin/all`

```
Exception in MainController.php line 37:
Can not found the Controller ( App\Http\Controllers\AdminController )
```

**Comment by serverfire** [comment]
@robincsamuel you have a controller ( AdminController  ) link in links table that not exit

**Comment by robincsamuel** [comment]
Thanks! Will it work if i create Admin/UserController. I mean to use a subfolder in controllers
