### ISSUE TITLE
Add a User Management section

### ISSUE THREAD

**Issue by alenoosh** [serverfireteam/panel#17]
We need to add a user management section with feature of assigning permissions to roles of users.

**Comment by jamespsterling** [comment]
Any idea when this will be complete?

**Comment by serverfire** [comment]
@jamespsterling we have working version of user management in user_roles branch you can use and upcoming version in next week

**Comment by jamespsterling** [comment]
@serverfire I've included "serverfireteam/panel": "dev-user_roles" in my composer configuration and updated. I get the following error when trying to hit the panel/login page. Am I missing a app/provider include?

```
FatalErrorException in dashboard.php line 30:
Class 'App\Role' not found
````

**Comment by serverfire** [comment]
@jamespsterling  try to remove app\role from link table or correct the link to model .  i think it should be : Serverfireteam\Panel\Role

**Comment by jamespsterling** [comment]
@serverfire Where would I correct the 'link to model'?

**Comment by jamespsterling** [comment]
@serverfire I found it, ```./config/panel.php```, add the 'Roles' index to the config list.

```
    'panelControllers' => array(
       'Admin', 'Link', 'Role' 
    ),
```
