### ISSUE TITLE
Created new controller, but not able to access

### ISSUE THREAD

**Issue by robincsamuel** [serverfireteam/panel#171]
I tried creating a new controller, and I get message `This url is not set yet!`

And then i tried to add the new link in `links`. but nothing happens! Page just reloads and the new link is not getting added.

I'm on Laravel 5.2 and uses 1.4.* of laravel panel

**Comment by robincsamuel** [comment]
Inserted manually into links table, got

```
Exception in MainController.php line 37:
Can not found the Controller ( Serverfireteam\Panel\UserController )
```

**Comment by serverfire** [comment]
@robincsamuel  you need to change laravelpanel controller name space in panel.php controllers value

**Comment by robincsamuel** [comment]
```
return array(
    
    'crudItems' => array(
       
    ),
    'panelControllers' => array(
       'Admin', 'Link' 
    ),
    'logo'=>'packages/serverfireteam/panel/img/logo.png' // logo of Panel 
    
);
    
```

This is what i have in the panel.php.

Kindly let me know, what should be altered.

**Comment by serverfire** [comment]
change that to : 
```
return array(
    `controllers` => 'App\Controller\Admin'
    'crudItems' => array(

    ),
    'panelControllers' => array(
       'Admin', 'Link' 
    ),
    'logo'=>'packages/serverfireteam/panel/img/logo.png' // logo of Panel 

);
```

Replace that with your own name space

**Comment by msafayasar** [comment]
Same for me. I did what you suggested but did not solve or did not affect anything. @serverfire Can you please look at it?

This is my panel.php and my controllers are in app/Http/Controllers folder. Thanks.
```
return array(
  'controllers' => 'App\Http\Controllers',

  'crudItems' => array(

  ),
  'panelControllers' => array(
     'Admin',
     'Permission',
     'Role',
     'Link'
  ),
  'logo'=>'packages/serverfireteam/panel/img/logo.png' // logo of Panel
);

```

**Comment by msafayasar** [comment]
Solved. Sorry for interrupting. This was because of the 'main' attr in database. I set all my links' 'main' field to 1.(I don't know why)

**Comment by vramiguez** [comment]
Hi!, I know this is an old issue, but I'm having it too and the solution is not helping. This is what I have:

In my panel.php:
`
return array(
    'controllers' => 'App\Http\Controllers\Panel',

    'crudItems' => array(

    ),
    'panelControllers' => array(
       'Admin',
       'Permission',
       'Role',
       'Link'
    ),
    'logo'=>'packages/serverfireteam/panel/img/logo.png');
`

My controllers are in App\Http\Controllers\Panel. This is an example of part of one of the controllers:
`
<?php 

namespace App\Http\Controllers\Panel;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use \Serverfireteam\Panel\CrudController;

use Illuminate\Http\Request;

class CategoryController extends CrudController{
`

But everytime I try to access any custom panel, I get an error message:

`
(1/1) Exception
Controller not found ( \\App\Http\Controllers\Panel\CategoryController )
`

I already cleared cache and restarted the server several times, but not sure where is the error. I appreciate if you can let me know. 
I'm using Laravel 5.4.36 and Panel 1.5.*

Thanks in advanced.

**Comment by vramiguez** [comment]
Thanks for the quick answer. I will try again and will let you know.
