### ISSUE TITLE
LaravelPanel can't work with MongoDB

### ISSUE THREAD

**Issue by alenn-m** [serverfireteam/panel#173]
I installed LaravelPanel and it works fine with MySQL but when I switched on MongoDB it doesn't work. I'm using this package for MongoDB: https://github.com/jenssegers/laravel-mongodb and I need to extend models with different version of Eloquent.
So is there any chance that I override your models to use this model for MongoDB?

**Comment by serverfire** [comment]
@alenn-m we are interested to support MongoDB , we need to change the our model and how crud work , If you think you can change the way it work send pull request and we will add to package , thank you
