### ISSUE TITLE
Do not see class after name change

### ISSUE THREAD

**Issue by MammutCris** [serverfireteam/panel#174]
I entered the command, сreated migration controller configured
`php artisan panel:crud category`
And then I realized that I wanted to rename a class Category and this error pops
`FatalErrorException in dashboard.php line 31:
Class 'App\category' not found`
Moreover, even when the git moved to a place where previously discovered /panel is on error

**Comment by serverfire** [comment]
@MammutCris we are keeping a record of models and controller in table name links . you shoud change there too
