### ISSUE TITLE
Add ability to change namespaces of models and controllers

### ISSUE THREAD

**Issue by jh9aea** [serverfireteam/panel#175]
It is very uncomfortable to keep all code in root directories. For example I want my panel controllers to be in App\Http\Controllers\Panel.. So to keep crud config in db (`links`) maybe is not good idea. I would prefer something like this: 

```
// config/panel.php
'links' => [
 [ 
  'title' => 'Blog', 
  'controller' => 'App\Http\Controllers\Panel\BlogController',  
  'model' => 'App\Models\Post'
 ]
]
```

**Comment by serverfire** [comment]
@jh9aea we have config for setting namespace for admin panel 

Like this 
```
<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
return array(

    `controllers` => 'App\Http\Controllers\Admin',
    'crudItems' => array(

    ),
    'panelControllers' => array(
       'Admin', 'Link'    
    ),
    'logo'=>'packages/serverfireteam/panel/img/logo.png' // logo of Panel 

);

```

**Comment by jh9aea** [comment]
Yep! this is exactly what I need
sorry i didn't find it in docs
:+1:

**Comment by josx** [comment]
is it working? in which version? I am using 1.3 on laravel 5.1

**Comment by jh9aea** [comment]
my version is 1.4.1 and controllers namespace working fine

**Comment by josx** [comment]
So Maybe It is a version problem, Do you know if i can use 1.4.1 with laravel 5.2 (because doc explicitly point to use 1.3)

**Comment by jh9aea** [comment]
I have laravel 5.2

**Comment by terion-name** [comment]
This works for controllers, but what about models?
