### ISSUE TITLE
install error with Laravel 5.2 on MacBookk elCapitan

### ISSUE THREAD

**Issue by ChrisHe** [serverfireteam/panel#176]
Hi, new Laravel 5.2 project, running $php artisan panel:install gives the following
```
Copied Directory [/vendor/serverfireteam/panel/public] To [/public...]
Copied Directory [/vendor/serverfireteam/panel/src/views] To [/resources/...]
Copied Directory [/vendor/serverfireteam/rapyd-laravel/public/assets] To [/public...]
Publishing complete for tag []!
```
but then
`[PDO Exception] SQLSTATE[HY000]  [2002] no such file or directory`

Any ideas what I am doing wrong?
Thanks

**Comment by serverfire** [comment]
@ChrisHe there two possible problem here , 

1. you are running php artisan out site the VM  

2. your mysql have problem or you have mysql connections problem

**Comment by ChrisHe** [comment]
Thanks for the help - yes, it was problem using MAMP with v-hosts config

**Comment by serverfire** [comment]
@ChrisHe happy to help , let me know if you need anythings
