### ISSUE TITLE
Unable to link User Model or other new tables

### ISSUE THREAD

**Issue by SaintGiff** [serverfireteam/panel#177]
I'm revisiting your repo again as I feel it has great potential.  I've run into a few issues and one question right from the beginning.  For starters I'll say that I am installed on a fresh Laravel build.  The database is set properly and the connections are working fine.

Issue #1:  I created a link in the dashboard to the User model.  When I click that link I just get a white screen.  There is no header or footer.  No error messages of any kind.  Just a white screen.  I'm wondering if this is because the CRUD for user was not generated in Panel.  If so, how can one use this with Auth or Billing, that has it's own CRUD?

Issue #2: I ran a migration for a test table, and seeded it.  I then ran panel:crud to create a model and controller for that table.  I created a link in the dashboard for the test table, and that link displays the correct number of records in the table.  Unfortunately,  when I click the link I get nothing.  I have an option to import or export data, but it fails to show any of the records from the table and I do not have an add button.  

So no ability to do anything at all with the User table.  No ability to view, add, edit or delete records in a table from a model that was generated using panel:crud.

**Comment by serverfire** [comment]
@SaintGiff 
For your first problem , you have to create controller to for model . yes you can use models in other controllers .

2. are you sure you have define the filed list on controller ?

**Comment by SaintGiff** [comment]
Yes, actually I have defined the field lists in the controller.

**Comment by serverfire** [comment]
@SaintGiff please post your controller code here
