### ISSUE TITLE
How to Create a Gallery tutorial - Viewing an uploaded image in the admin panel

### ISSUE THREAD

**Issue by edwardpayton** [serverfireteam/panel#179]
Following the How to create an Image Gallery with managment system in 5 minutes tutorial, the panel list shows the image url, the edit page shows the image url, but clicking the image url returns this error:

`1/1 NotFoundHttpException in RouteCollection.php line 161:`

This is because the image doesnt return uploads in the URL. 

Changing the add image line in galleryController.edit  from:
`$this->edit->add('image', 'Image', 'file')->rule('required');`
to
`$this->edit->add('image', 'Image', 'file')->rule('required')->move('uploads');`
returns the correct url

**Comment by bloodymind** [comment]
I have the same problem ! Any update about it ?

**Comment by EdwardJPayton** [comment]
You can add ->move() to the line in the GalleryController and it works, ie:
`$this->edit->add('image',` 'Image', 'file')->rule('required')->move('uploads');`

**Comment by bloodymind** [comment]
Well , i did that before but it's really working ,  i have always this problem :

`$this->edit->add('photo', 'Photo', 'file')->rule('required')->move(public_path().'/uploads/');`

Result :
 
`FileNotFoundException in File.php line 37:
The file "/Applications/XAMPP/xamppfiles/temp/phpkHAh4o" does not exist`

PS: File name is stored in DB and file itself is uploaded to my dir.

**Comment by AaronLayton** [comment]
I get the same issue - is there any solution to this

**Comment by bloodymind** [comment]
Nop :/

**Comment by serverfire** [comment]
do you still have this problem with last version ?
