### ISSUE TITLE
disable field

### ISSUE THREAD

**Issue by lassouani** [serverfireteam/panel#180]
I saw the documntation , I wonder how to disable a field , if admin  would change  I would forbid him to modify a user's information ,
i look for the syntaxe to do this.
thank you

**Comment by serverfire** [comment]
@lassouani  we don't have this right now

**Comment by johnval990** [comment]
You can disable a field this way:
`$nameField = $this->edit->add('name', 'Name', 'text');`
`$nameField->attributes = ['disabled' => 'disabled'];`
