### ISSUE TITLE
Call to undefined method Serverfireteam\Panel\libs\dashboard::getItems()

### ISSUE THREAD

**Issue by jackyliang** [serverfireteam/panel#183]
I am on Laravel version `5.1.30` after installing LaravelPanel using `1.3.*` for `composer.json`. 

***Note***: I initially did install `1.4^` using the composer command (not by adding it manually into `composer.json`), but that doesn't work for Laravel 5.1.\*, so I manually edited `composer.json` to `1.3.*` and ran `composer update`.

I was able to successfully migrate the tables (verified using Sequel Pro) as well as access the admin login panel. However, once I log into the panel, I get the following error:

    FatalErrorException in 4a6da9cc51a916eb28f6ad9fed5b7944 line 15:
    Call to undefined method Serverfireteam\Panel\libs\dashboard::getItems()

I did a `grep` for the function `getItems()` and it did not return any results. What's inside `libs/dashboard` is the following, which does not contain `getItems()`

```

<?php
namespace Serverfireteam\Panel\libs;


class dashboard
{    
    
    public static $urls; 
    
    public static function create()
    {
        self::$urls = \Config::get('panel.panelControllers');
        
        $config    = \Serverfireteam\Panel\Link::all();
        $dashboard = array();

        // Make Dashboard Items
        foreach ($config as $key => $value) {                        

	    $modelName = $value['url'];           
            if ( in_array($modelName, self::$urls)) {
               $model = "Serverfireteam\Panel\\".$modelName;
            } else {
               $appHelper = new AppHelper(); 
               $model = $appHelper->getNameSpace() . $modelName;
            }

            //if (class_exists($value)) {
            $dashboard[] = array(
                'title'	  => $value['display'],
                'count'	  => $model::all()->count(),
                'showListUrl' => 'panel/' . $modelName . '/all',
                'addUrl'	  => 'panel/' . $modelName . '/edit',
            );   
        }

	return $dashboard;
    }
}

```

I am wondering what the issue is?

**Comment by jackyliang** [comment]
I fixed this by completely removing LaravelPanel from composer and re-installing it.

**Comment by campherkurt** [comment]
Ok this is happening for me as well.

@jackyliang  How did you completely remove it?

**Comment by serverfire** [comment]
@jackyliang @campherkurt please use last version of laravelpanel with laravel 5.2
