### ISSUE TITLE
Can not found the Controller ( App\Http\Controllers\LinkController ) on new install

### ISSUE THREAD

**Issue by jackyliang** [serverfireteam/panel#184]
I am on Laravel version `5.1.30` after installing LaravelPanel using `1.3.*` for `composer.json`

The installation was a success, and I performed all the steps in [here](http://laravelpanel.com/docs/master/manual-installation).

I was able to log in and change my account settings, however, when I click on the "Link" panel, I get the following error:

```
Exception in MainController.php line 37:
Can not found the Controller ( App\Http\Controllers\LinkController )
```

I checked out `App\Http\Controllers\LinkController` and it does not exist a `LinkedController`, but under the `vendor/serverfireteam/panel/src/controllers/` there is indeed a `LinkController.php`

**Comment by uF7264** [comment]
Same here, could you resolve the issue already?

**Comment by jackyliang** [comment]
@uF7264 I just removed the `Links` table in as it was just a test table. Solved the issue. I don't know a direct fix to it, however.

**Comment by serverfire** [comment]
@jackyliang @uF7264  please use last laravelpanl with laravel 5.2
