### ISSUE TITLE
Redirect after saving

### ISSUE THREAD

**Issue by RichardLindhout** [serverfireteam/panel#186]
How can I redirect a user after saving something succesfully?

**Comment by serverfire** [comment]
@RichardLindhout  you can listen on model changes event and redirect users

**Comment by lbm-services** [comment]
can you provide an example?
I tried 
```
  Models\blog_posts::updated(function() {
                 return redirect('panel/blog_posts/all');
        });
```
but with no success.

**Comment by RichardLindhout** [comment]
I would recommend to use http://labs.infyom.com/laravelgenerator/docs/5.3/introduction
