### ISSUE TITLE
ERRO elFinder 2.0 - Invalid Backend configuration. Readable voules not available.

### ISSUE THREAD

**Issue by Renanh** [serverfireteam/panel#188]
I can not insert an image using the component:
"$this->edit->add('text', 'text', 'redactor');"

ERRO: Invalid Backend configuration. Readable voules not available.

**Comment by terion-name** [comment]
Create `files` folder un `public` or change `files` to `uploads` in `config/elfinder.php` at `13` ad `68` rows

**Comment by Renanh** [comment]
Thanks, but now when I insert an image returns this error, how do I fix? 

**Array to string conversion**

![image](https://cloud.githubusercontent.com/assets/8283925/13551932/2683d14a-e329-11e5-8029-dd6b1a4c758e.png)

**Comment by terion-name** [comment]
dunno, don't have this error

**Comment by Renanh** [comment]
when you create the folder, you include an image and returns this error.
only to create grazing file directory in public?

2016-03-06 14:50 GMT-03:00 Terion <notifications@github.com>:

> dunno, don't have this error
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serverfireteam/panel/issues/188#issuecomment-192945397>
> .
>



-- 
*Att. Renanh Lima*
*Contatos:*
*(81)98347-60**65  **(OI)*
*(81)99592-0226  (TIM)*
*(81)99220-9449*  *(CLARO)*

**Comment by serverfire** [comment]
@Renanh Please try fresh laravel and  laravelpanel install  and give it a try .

if you have same error send us js log and laravel log

**Comment by Renanh** [comment]
Presented another error:

![erro](https://cloud.githubusercontent.com/assets/8283925/14906412/7b730936-0d91-11e6-8d15-7ac432cda9c8.JPG)


the column in the database must be VARCHAR?
