### ISSUE TITLE
Add Event Handler in Panel

### ISSUE THREAD

**Issue by alenoosh** [serverfireteam/panel#19]
We can add event handlers to enable customization of different actions in panel. For example we can add an 'On Delete' event handler to perform certain tasks before deleting a record or we can add an 'On Insert' event handler to perform certain tasks (like doing some kind of validation) before inserting a record and so on ... We can also add some default event handlers so that users can use them if they need to.

**Comment by RichardLindhout** [comment]
+1 I need this

**Comment by RichardLindhout** [comment]
+1

**Comment by serverfire** [comment]
@RichardLindhout  if you need that event handler , we can work together to create it .
 
won't be hard , as laravel have event system , we need create few event class and fire them in few part of code

**Comment by RichardLindhout** [comment]
@serverfire Nice! Except I think I don't have enough experience with Laravel to do that ;(

**Comment by serverfire** [comment]
@RichardLindhout  OKay , will try to add this soon as possible

**Comment by serverfire** [comment]
added to last version
