### ISSUE TITLE
The cipher and / or key length are invalid in admin panel page

### ISSUE THREAD

**Issue by kilis** [serverfireteam/panel#190]
Hi,
I just installed panel and i have this problem.
`RuntimeException in EncryptionServiceProvider.php line 31:
No supported encrypter found. The cipher and / or key length are invalid.`
Key is installed.

**Comment by serverfire** [comment]
@kilis this is a general problem with laravel , check if first page of app is working or not

**Comment by surgiie** [comment]
@kilis  im not sure if you solved this or not, but you Ive found that that if you if you dont have a .env file with an app key set you will have this error. Make sure you have a .env file in your root folder. Usually a fresh laravel project comes with a .env.example. If you rename this to .env for windows or .env. for linux and run the command php aritsan key:generate, this usually fixes the problem. I hope this helps.
