### ISSUE TITLE
Foreign Key

### ISSUE THREAD

**Issue by surgiie** [serverfireteam/panel#191]
How can i get the foreign key value to show up in the grid instead of the id?

**Comment by serverfire** [comment]
@surgiie you can edit view of panel to work they way you want

**Comment by surgiie** [comment]
@serverfire where can i find the panel view? thanks!

**Comment by surgiie** [comment]
@serverfire I found the views but i suppose i should clarify a bit better what im trying to do as Im not having luck and would appreciate some guidance.

I have a StudentController to display student information and have no problem displaying the grid with
$this->grid->add('field','label'). But one of my fields is a foreign key that comes from another table called orientation_dates so I can add it no prob as follows:

$this->grid->add('orientation_date_id', 'Date Attending');

but of course this shows the id. What i want is to display the date column from this foreign object.
I tried tacking date(column name) to it:

$this->grid->add('orientation_date_id.date', 'Date Attending'); 

but this returns the grid with it displaying {{$orientation_date_id->date}}

I have a relationship function linked in the Student model so im not sure what im missing.:((

Thanks for any help you may offer!:)

**Comment by surgiie** [comment]
FAQ section answered my question
