### ISSUE TITLE
Admin Panel

### ISSUE THREAD

**Issue by RoshanPrajapati** [serverfireteam/panel#194]
Hello, i m new for Laravel 
I want to use panel so i follow the steps given for panel.
I run " composer require serverfireteam/panel ", after install Laravel.
In this step it ask for " git@github.com's password: " so what i do ?
can you please give me suggestion for install panel.

**Comment by serverfire** [comment]
@RoshanPrajapati there is chance you had lot of request to github server and github asking your user and password
