### ISSUE TITLE
Export to Excel sync/displaying foreign key

### ISSUE THREAD

**Issue by surgiie** [serverfireteam/panel#199]
When filtering the grid with filter and exporting to excel, the excel file still displays ALL results in excel instead of just the FILTERED results. 

Also, is there anyway to display foreign key value in excel results instead of id?

**Comment by serverfire** [comment]
@surgiie yes we do have this problem , 
We need to filter the result before giving it to excel export 
Can you send a pull request for it ?

**Comment by surgiie** [comment]
Still somewhat new to laravel and php. How could i get filtered data back in the export controller? @serverfire

**Comment by serverfire** [comment]
@surgiie you need to edit export excel controller yo use filter data , pass that data with ajax
