### ISSUE TITLE
hmm I have a problem

### ISSUE THREAD

**Issue by texnika01** [serverfireteam/panel#2]
![error](https://cloud.githubusercontent.com/assets/10789177/5994296/005fb782-aa76-11e4-94c3-2718bf0a68ad.png)
------------------------
URL in http://project/panel/login .....

composer.js : {

"name": "laravel/laravel",

"description": "The Laravel Framework.",

"keywords": ["framework", "laravel"],

"license": "MIT",

"type": "project",

"require": {

"laravel/framework": "4.2.*"

},

"require": {

"serverfireteam/panel": "1.1.*"

},

"autoload": {

"classmap": [

"app/commands",

"app/controllers",

"app/models",

"app/database/migrations",

"app/database/seeds",

"app/tests/TestCase.php"

]

},

"scripts": {

"post-install-cmd": [

"php artisan clear-compiled",

"php artisan optimize"

],

"post-update-cmd": [

"php artisan clear-compiled",

"php artisan optimize"

],

"post-create-project-cmd": [

"php artisan key:generate"

]

},

"config": {

"preferred-install": "dist"

},

"minimum-stability": "stable"

}

**Comment by texnika01** [comment]
URL in http://project/panel/login .....

composer.js : {

"name": "laravel/laravel",

"description": "The Laravel Framework.",

"keywords": ["framework", "laravel"],

"license": "MIT",

"type": "project",

"require": {

"laravel/framework": "4.2.*"

},

"require": {

"serverfireteam/panel": "1.1.*"

},

"autoload": {

"classmap": [

"app/commands",

"app/controllers",

"app/models",

"app/database/migrations",

"app/database/seeds",

"app/tests/TestCase.php"

]

},

"scripts": {

"post-install-cmd": [

"php artisan clear-compiled",

"php artisan optimize"

],

"post-update-cmd": [

"php artisan clear-compiled",

"php artisan optimize"

],

"post-create-project-cmd": [

"php artisan key:generate"

]

},

"config": {

"preferred-install": "dist"

},

"minimum-stability": "stable"

}

**Comment by siavash13** [comment]
it seems there is nothing wrong with your `composer.json` file, could you please create a new laravel project from scratch with the following command 
`composer create-project laravel/laravel your-project-name --prefer-dist`
and then follow the `read.me` file of this package 
if you still face the same issue again please let us know we'd help you to fix it

**Comment by texnika01** [comment]
Ha.. now works.Maybe the problem is with  2 requir :
"require": {
"laravel/framework": "4.2.*"
},
"require": {
"serverfireteam/panel": "1.1.*"
},

**Comment by texnika01** [comment]
thank you
