### ISSUE TITLE
files missing

### ISSUE THREAD

**Issue by gan068** [serverfireteam/panel#20]
http://demo.serverfire.net/packages/zofe/rapyd/assets/redactor/css/redactor.css
http://demo.serverfire.net/packages/zofe/rapyd/assets/redactor/jquery.browser.min.js
http://demo.serverfire.net/packages/zofe/rapyd/assets/redactor/redactor.min.js
http://demo.serverfire.net/packages/zofe/rapyd/assets/redactor/jquery.browser.min.js
http://demo.serverfire.net/packages/zofe/rapyd/assets/redactor/redactor.min.js

**Comment by alenoosh** [comment]
@gan068 These files are not used anymore, I removed the links.

Thanks for reporting
