### ISSUE TITLE
Runtime Exception

### ISSUE THREAD

**Issue by huntercarter** [serverfireteam/panel#202]
This happens when I try to install via Composer and Terminal:

> [RuntimeException]                                                                                                                   
> Could not load package intervention/image in http://packagist.org: [UnexpectedValueException] Could not parse version constraint 4.  
> x.x: Invalid version string "4.x.x"

**Comment by serverfire** [comment]
@huntercarter please give us version of laravel and laravelpanel

**Comment by OnYXCoding** [comment]
having the same issue here. 

Laravel v5.2.29
Panel v1.4

[RuntimeException]
 Could not load package intervention/image in http://packagist.org: [UnexpectedValueException]
 Could not parse version constraint 4.x.
 x: Invalid version string "4.x.x"

[UnexpectedValueException]
 Could not parse version constraint 4.x.x: Invalid version string "4.x.x"
