### ISSUE TITLE
Undefined Entity

### ISSUE THREAD

**Issue by SapioBeasley** [serverfireteam/panel#203]
After a little time of developing from a fresh install of both laravel and your package, I ran into this error:

`ErrorException in CrudController.php line 25:
Undefined index: entity`

From the panel everything is fine, but from my apps front end is where I received the error. 

*Route*
```php
Route::get('/campaigns/{campaign}', [
	'as' => 'campaigns.show',
	'uses' => 'CampaignController@show'
]);
```

*Controller*
```php
class CampaignController extends CrudController
{
// Panel Logic
	public function all($entity)
	{
		parent::all($entity);

		// Filter Logic

		// Grid Logic

		return $this->returnView();
	}

	public function  edit($entity)
	{
		parent::edit($entity);

		// Edit Logic

		return $this->returnEditView();
	}

// App Logic

	/**
	* Show the application dashboard.
	*
	* @return \Illuminate\Http\Response
	*/
	public function show(Request $request)
	{
		return view('campaigns.show');
	}
```

I would like to keep all logic regarding campaigns to remain in one single controller, so I snooped around to find how I can fix.

Very simply I edited line 25 in the CrudController to fix this error from 

```php
$this->setEntity($routeParamters['entity']);
``` 

to

```php
$this->setEntity(isset($routeParamters['entity']) ? $routeParamters['entity'] : null);
``` 

This works for me, but I am not sure what may break as far as the entities go down the line. If all looks good, It would be nice to have this edit in future pushes. Great package by the way, I have been looking for a package like this for a while. Thank you

**Comment by serverfire** [comment]
@SapioBeasley we do suggest you to separate front-end and admin controller .
 if you want to keep both in same file , pass empty entity in your route

**Comment by SapioBeasley** [comment]
Noted, thank you.

@SapioBeasley <https://github.com/SapioBeasley> we do suggest you to
separate front-end and admin controller .
if you want to keep both in same file , pass empty entity in your route

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/serverfireteam/panel/issues/203#issuecomment-206709766>
