### ISSUE TITLE
Class 'App\Role' not found

### ISSUE THREAD

**Issue by SapioBeasley** [serverfireteam/panel#204]
After an update using instructions from [here](http://laravelpanel.com/docs/master/update)

I now get 

`ErrorException in dashboard.php line 45:
Fatal error: Class 'App\Role' not found`

when visiting `/panel/Link/all` or `/panel/Link/edit`or any other resource add or edit.

**Comment by ChrisHe** [comment]
suggest check that your config/panel.php has 'Link entry in the 'panelControllers' array
and you do not have an App/link model. Also check the actual Links table and ensure 
your links table has entry of display = 'Links',  url = 'Link',  (Links is a Panel model provided in vendors/...
HTH

**Comment by jbajou** [comment]
Just got the same issue. Fixed it by making sure the panelControllers array in config/panel.php was containing the following:
`       'Admin',
       'Permission',  
       'Role',  
       'Link'`
