### ISSUE TITLE
Custom Authentication

### ISSUE THREAD

**Issue by surgiie** [serverfireteam/panel#207]
Im currently using this panel for a project that requires a custom authentication. It is a CAS token based authentication system and Im wondering where the auth files are for this panel or what files i need to edit to integrate this custom authentication? 

Thanks!

**Comment by serverfire** [comment]
@surgiie you need to edit here : https://github.com/serverfireteam/panel/blob/master/src/Serverfireteam/Panel/PanelServiceProvider.php#L42
