### ISSUE TITLE
How to delete serverfireteam/panel package with its files from laravel 5.1

### ISSUE THREAD

**Issue by karnagowtham** [serverfireteam/panel#209]
we need step by step procedure to remove panel from our laravel project.

**Comment by karnagowtham** [comment]
Hi dear

I just submit my queries into https://github.com like below

serverfireteam/panel <https://github.com/serverfireteam/panel> How to
delete serverfireteam/panel package with its files from laravel 5.1
<https://github.com/serverfireteam/panel/issues/209>
#209 opened 18 minutes ago
<https://github.com/issues?q=is%3Aissue+is%3Aopen+author%3Akarnagowtham>and

serverfireteam/panel <https://github.com/serverfireteam/panel> How to
remove server fireteam panel from laravel 5.1
<https://github.com/serverfireteam/panel/issues/208>
#208 opened 27 minutes ago

But your team just close my above two queries, then how i solve my issue,
the server fireteam panel team only responsible to these kind of issue, i
need solution for an above two issue.







On Tue, May 3, 2016 at 12:32 PM, Serverfire <notifications@github.com>
wrote:

> Closed #209 <https://github.com/serverfireteam/panel/issues/209>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/serverfireteam/panel/issues/209#event-648489053>
>



-- 
With thanks from,

*Gowtham Karna*

*Web Developer,*
*iCLIENT Technologies.*
*Mob  : +91 -8056606341  *
*Mail *: gowtham@iclienttech.com

**Comment by serverfire** [comment]
@karnagowtham  remove it from vendor and public folder do a composer dump autoload

**Comment by karnagowtham** [comment]
Hi dear

We done these things already but @ final  its shows only error., like below.

(01:57:22  IST) Rahim:
Warning: Ambiguous class resolution, "elFinderVolumeDropbox" was found in
both
"/home/vagrant/Code/icart-main/vendor/barryvdh/elfinder-builds/php/elFinderVolumeDropbox.class.php"
and
"/home/vagrant/Code/icart-main/vendor/studio-42/elfinder/php/elFinderVolumeDropbox.class.php",
the first will be used.
Warning: Ambiguous class resolution, "elFinder" was found in both
"/home/vagrant/Code/icart-main/vendor/barryvdh/elfinder-builds/php/elFinder.class.php"
and
"/home/vagrant/Code/icart-main/vendor/studio-42/elfinder/php/elFinder.class.php",
the first will be used.
Warning: Ambiguous class resolution, "elFinderConnector" was found in both
"/home/vagrant/Code/icart-main/vendor/barryvdh/elfinder-builds/php/elFinderConnector.class.php"
and
"/home/vagrant/Code/icart-main/vendor/studio-42/elfinder/php/elFinderConnector.class.php",
the first will be used.
Warning: Ambiguous class resolution, "elFinderVolumeS3" was found in both
"/home/vagrant/Code/icart-main/vendor/barryvdh/elfinder-builds/php/elFinderVolumeS3.class.php"
and
"/home/vagrant/Code/icart-main/vendor/studio-42/elfinder/php/elFinderVolumeS3.class.php",
the first will be used.
Warning: Ambiguous class resolution, "S3SoapClient" was found in both
"/home/vagrant/Code/icart-main/vendor/barryvdh/elfinder-builds/php/elFinderVolumeS3.class.php"
and
"/home/vagrant/Code/icart-main/vendor/studio-42/elfinder/php/elFinderVolumeS3.class.php",
the first will be used.
Warning: Ambiguous class resolution, "elFinderVolumeLocalFileSystem" was
found in both
"/home/vagrant/Code/icart-main/vendor/barryvdh/elfinder-builds/php/elFinderVolumeLocalFileSystem.class.php"
and
"/home/vagrant/Code/icart-main/vendor/studio-42/elfinder/php/elFinderVolumeLocalFileSystem.class.php",
the first will be used.
Warning: Ambiguous class resolution, "elFinderVolumeDriver" was found in
both
"/home/vagrant/Code/icart-main/vendor/barryvdh/elfinder-builds/php/elFinderVolumeDriver.class.php"
and
"/home/vagrant/Code/icart-main/vendor/studio-42/elfinder/php/elFinderVolumeDriver.class.php",
the first will be used.
Warning: Ambiguous class resolution, "elFinderVolumeFTPIIS" was found in
both
"/home/vagrant/Code/icart-main/vendor/barryvdh/elfinder-builds/php/elFinderVolumeFTPIIS.class.php"
and
"/home/vagrant/Code/icart-main/vendor/studio-42/elfinder/php/elFinderVolumeFTPIIS.class.php",
the first will be used.
Warning: Ambiguous class resolution, "elFinderVolumeFTP" was found in both
"/home/vagrant/Code/icart-main/vendor/barryvdh/elfinder-builds/php/elFinderVolumeFTP.class.php"
and
"/home/vagrant/Code/icart-main/vendor/studio-42/elfinder/php/elFinderVolumeFTP.class.php",
the first will be used.
Warning: Ambiguous class resolution, "elFinderVolumeMySQL" was found in
both
"/home/vagrant/Code/icart-main/vendor/barryvdh/elfinder-builds/php/elFinderVolumeMySQL.class.php"
and
"/home/vagrant/Code/icart-main/vendor/studio-42/elfinder/php/elFinderVolumeMySQL.class.php",
the first will be used.
Warning: Ambiguous class resolution, "elFinderPluginWatermark" was found in
both
"/home/vagrant/Code/icart-main/vendor/barryvdh/elfinder-builds/php/plugins/Watermark/plugin.php"
and
"/home/vagrant/Code/icart-main/vendor/studio-42/elfinder/php/plugins/Watermark/plugin.php",
the first will be used.
Warning: Ambiguous class resolution, "elFinderPluginNormalizer" was found
in both
"/home/vagrant/Code/icart-main/vendor/barryvdh/elfinder-builds/php/plugins/Normalizer/plugin.php"
and
"/home/vagrant/Code/icart-main/vendor/studio-42/elfinder/php/plugins/Normalizer/plugin.php",
the first will be used.
Warning: Ambiguous class resolution, "elFinderPluginAutoResize" was found
in both
"/home/vagrant/Code/icart-main/vendor/barryvdh/elfinder-builds/php/plugins/AutoResize/plugin.php"
and
"/home/vagrant/Code/icart-main/vendor/studio-42/elfinder/php/plugins/AutoResize/plugin.php",
the first will be used.
Warning: Ambiguous class resolution, "elFinderPluginSanitizer" was found in
both
"/home/vagrant/Code/icart-main/vendor/barryvdh/elfinder-builds/php/plugins/Sanitizer/plugin.php"
and
"/home/vagrant/Code/icart-main/vendor/studio-42/elfinder/php/plugins/Sanitizer/plugin.php",
the first will be used.



On Tue, May 3, 2016 at 1:07 PM, Serverfire <notifications@github.com> wrote:

> @karnagowtham <https://github.com/karnagowtham> remove it from vendor and
> public folder do a composer dump autoload
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/serverfireteam/panel/issues/209#issuecomment-216459177>
>



-- 
With thanks from,

*Gowtham Karna*

*Web Developer,*
*iCLIENT Technologies.*
*Mob  : +91 -8056606341  *
*Mail *: gowtham@iclienttech.com

**Comment by serverfire** [comment]
this is studio-42/elfinder error , you should ask them , your problem is you have two version of elfinder in same time i think , we don't have laravel support here , thank you
