### ISSUE TITLE
Panel install a bit too overambitious

### ISSUE THREAD

**Issue by atrauzzi** [serverfireteam/panel#210]
When I run `./run artisan panel:install`, it has the unfortunate sideffect of running the install for EVERY package in my laravel project.

It would be nice if the command it issued restricted the asset and config copy just for the panel packages.  Not everything.

**Comment by serverfire** [comment]
@atrauzzi  can you send pull request for this ?

**Comment by atrauzzi** [comment]
Sorry, won't have time for this.  Although I'm sure it's simple enough for you to address.

**Comment by serverfire** [comment]
@atrauzzi thank you for your suggestion , we will think about this later , if it is very important for you , you can send me mail and talk about it , info@serverfire.net
