### ISSUE TITLE
We need to login...

### ISSUE THREAD

**Issue by zile-lhs** [serverfireteam/panel#22]
...somehow.

**Comment by seanthepottingshed** [comment]
+1

**Comment by alenoosh** [comment]
@zile-lhs We have disabled the 'Profile Edit' feature from demo, so users can't change the username. Now you can login as usual : 
Username: admin@change.me
Password: 12345

**Comment by zile-lhs** [comment]
Thanks, it's working now.

**Comment by alenoosh** [comment]
@zile-hls You're welcome :)
