### ISSUE TITLE
Login error Laravel 5.2

### ISSUE THREAD

**Issue by kakadanhem** [serverfireteam/panel#221]
Follow the installation instruction and installed successfully. But when login error appear with message:
TokenMismatchException in VerifyCsrfToken.php line 67
-----------------------------------------------------------------------
I solved this issue by adding
< meta name="csrf-token" content="{{ csrf_token() }}" />

in panelView\master.blade.php

**Comment by serverfire** [comment]
@kakadanhem fixed
