### ISSUE TITLE
How to delete Model or Controller

### ISSUE THREAD

**Issue by zhabir** [serverfireteam/panel#222]
I create the model and the controller using the panel: crud. For example, _php artisan panel: crud City_. Then I want that name was Cities, rather than the City. I delete models City and CityController controller. Then, create a _php artisan panel: crud Cities_. But an error 
```
FatalErrorException in dashboard.php line 45:
Class 'App\City' not found.
```

**Comment by serverfire** [comment]
You should remove the model record in link table

On Saturday, May 21, 2016, zhanibek smagul <notifications@github.com> wrote:

> I create the model and the controller using the panel: crud. For example, *php
> artisan panel: crud* City. Then I want that name was Cities, rather than
> the City. I delete models City and CityController controller. Then, create
> a *php artisan panel: crud Cities*. But an error
>
> FatalErrorException in dashboard.php line 45:
> Class 'App \ City' not found.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/serverfireteam/panel/issues/222>
>


-- 
Best regards
Alireza Aboutalebi
Serverfire.net

**Comment by zhabir** [comment]
Thank you. It worked
