### ISSUE TITLE
[Symfony\Component\Debug\Exception\FatalErrorException] Class 'Serverfireteam\Panel\PanelServiceProvider' not found

### ISSUE THREAD

**Issue by rishisain** [serverfireteam/panel#223]
Hi I have installed the Laravel 5.2.31 and after that when I execute this following command: php artisan panel:install then I got this Error message: 
[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'Serverfireteam\Panel\PanelServiceProvider' not found

I have followed all the instruction which you have mention this site: http://laravelpanel.com/docs/master/automatic-installation

But after that I got this message. This is my project URL: http://webdevelopcompany.com/fundmyjustice/laravel/

I have attached all the required documents. Please help me to find out any solution.
![app](https://cloud.githubusercontent.com/assets/10656078/15492643/3997ae0e-219b-11e6-9ff4-9971e709a636.png)
![composerjson](https://cloud.githubusercontent.com/assets/10656078/15492644/39988900-219b-11e6-85d8-05f1fe51329b.png)
![1](https://cloud.githubusercontent.com/assets/10656078/15492645/399eb7bc-219b-11e6-935d-41293fdf2a82.png)

**Comment by serverfire** [comment]
@rishisain please use last version of laravel with laravel 5.2
