### ISSUE TITLE
Dropdown Box

### ISSUE THREAD

**Issue by gksingh35** [serverfireteam/panel#227]
Is it possible to apply dropdownbox where the values come from some other table?

**Comment by serverfire** [comment]
Q: How can I create a drop down field with reference to another CRUD item. Also how can I show that field in list of records ?

A: You can use the 'options' method to pass the values from another table to drop down fields. This method gets an array of key/values, for example if the name of the model you want to get the values from is 'Company', you can define your field like this :

$this->edit->add('field-name', 'label', 'select')->options(\Company::lists("name", "id")->all());

Read the fag : http://laravelpanel.com/docs/master/faq
