### ISSUE TITLE
Maximum function nesting level of '100' reached, aborting!

### ISSUE THREAD

**Issue by zebi-rajpot** [serverfireteam/panel#232]
how to solve that issue.
i installed your panel in fresh laravel and i'm using wamp.

i found some solutions on internet like edit php.ini and increase the value of xdebug.max_nesting_level.
but in my php.ini there is no such a option available .!!

**Comment by msafayasar** [comment]
@zebi-rajpot did you find a solution? I am facing same problem when running 
`php artisan panel:crud `
