### ISSUE TITLE
Route for custom location models

### ISSUE THREAD

**Issue by glasnostra** [serverfireteam/panel#233]
I installed the panel for my recent project and it work great... I try to add new model using `panel:createmodel` and the controller using `panel:createcontroller` because I want to move all my model to Models/ directory. I add new link with display `Posts` and link `Models\Post`.

It work and show the amount of Post in the dashboard. but I get error when try to show list or add new post

```
NotFoundHttpException in RouteCollection.php line 161:
```

do I miss some step for a custom location models? I tried re-read the documentation but seems can't find the answer, I know there something I miss out.. hope someone can pointing it out...

sorry for bad English

**Comment by vramiguez** [comment]
Hi, I'm having the same issue. Were you able to find a solution @glasnostra ?
Wondering if @serverfire could give us a hand. 
Thanks in advanced.

**Comment by serverfire** [comment]
Right now we only  support models in their original path . you can't put them in models folder

**Comment by serverfire** [comment]
We added that, please install from master branch and give us feedback
