### ISSUE TITLE
Roles/Permissions Documentation

### ISSUE THREAD

**Issue by warksit** [serverfireteam/panel#235]
Is there any? I'm struggling to get started. 

1. Do I really need to create a permission for [entity]all [entity]edit for all my various entities? 
2. What does the crudItems in the config do? 
3. Can I just show Links/Roles/Permissions/Admins menu items to super admins and my entities for others?

Appreciate any help

**Comment by warksit** [comment]
3. Seems not, I have just deleted them from the links table and also removed them from panelControllers in config/panel.php

**Comment by serverfire** [comment]
@warksit 
2 . we don't need it anymore , removed today 
3. i think you can make a permissions for only super admins with that menu item , give it a try
