### ISSUE TITLE
There are no commands defined in the "panel" namespace.

### ISSUE THREAD

**Issue by bgachip** [serverfireteam/panel#238]
I followed the install notes, but i couldn't install blog and panel parts.

I use 5.2 Laravel.

I got below error when i run php artisan blog:install
[Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "panel" namespace.

What's the solution for this problem?

**Comment by warksit** [comment]
Have you added the service provider?

**Comment by amitkumar4268** [comment]
yes and i am using laravel 5.2.41

**Comment by amitkumar4268** [comment]
'providers' => array(
        Serverfireteam\Panel\PanelServiceProvider::class
    )

    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        Serverfireteam\Panel\PanelServiceProvider::class

    ],
like this and let me know if i am doing anything wrong

**Comment by amitkumar4268** [comment]
[Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "panel" namespace.  error showing on terminal

**Comment by danis963** [comment]
After add "Serverfireteam\Panel\PanelServiceProvider::class" in Providers, run composer update.
After that run php artisan panel:install.
Best wishes.
Daniel

**Comment by vishalmote** [comment]
There is **kernel.php** file inside a console folder, there is **commands** variable inside **kernel.php** add your command class there

```
protected $commands = [
         Commands\Inspire::class,
        Commands\PullScada::class,
    ];
```

like I have added my command class `Commands\PullScada::class,`

**Comment by cojocaru3** [comment]
I'm also getting this issue, any solutions ?
