### ISSUE TITLE
installation failed reverting ./composer.json to its original content

### ISSUE THREAD

**Issue by Monilal** [serverfireteam/panel#239]
"composer require serverfireteam/panel" not working its return an error like "installation failed reverting ./composer.json to its original content",

**Comment by serverfire** [comment]
manually edit the composer.json

**Comment by Monilal** [comment]
{
	"name": "laravel/laravel",
	"description": "The Laravel Framework.",
	"keywords": ["framework", "laravel"],
	"license": "MIT",
	"require": {
		"laravel/framework": "4.2.*"
	},
	"autoload": {
		"classmap": [
			"app/commands",
			"app/controllers",
			"app/models",
			"app/database/migrations",
			"app/database/seeds",
			"app/tests/TestCase.php"
		]
	},
	"scripts": {
		"post-install-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-update-cmd": [
			"php artisan clear-compiled",
			"php artisan optimize"
		],
		"post-create-project-cmd": [
			"php artisan key:generate"
		]
	},
	"config": {
		"preferred-install": "dist"
	},
	"minimum-stability": "stable"
}

here is my composer.json, I'm new in laraval

**Comment by serverfire** [comment]
you should get help in stackoverflow

**Comment by warksit** [comment]
Use Laravel 5.2
