### ISSUE TITLE
Translate the panel

### ISSUE THREAD

**Issue by Extazx2** [serverfireteam/panel#250]
Hello,
I followed your instructions right there : http://laravelpanel.com/docs/master/override-lang-files
but i'm not that good in english,
so , i created the "resources/lang/vendor/panel/" and i put fields.php translated in the language i wanted
i did the same with rapyd, but nothing changed, what did i do wrong ?

**Comment by serverfire** [comment]
did you change lang in your config file ? please send pull request for that lang

**Comment by Extazx2** [comment]
holy moly. Totally forgot about the config file, my bad !
