### ISSUE TITLE
How works roles

### ISSUE THREAD

**Issue by felipegarcial** [serverfireteam/panel#257]
How can I work with roles, for example all options rendered for any role user, the Idea is for a specificrole in the dashboard render specific things, but I dont know how works because in the documentation you don't mention this topic.

Regards and thanks for this awsome tool.

**Comment by lonerunner** [comment]
I am interested in this too, i can't figure out how roles and permissions works, i have setup panel and added a new user, created few roles and few permissions, but i don't understand url part in permission, none of the url's i tested not working and second user i created with limited role can't open any page when loged in but see all of the pages in the menu on the left. Have you figured out this ?

**Comment by hamdiwanis** [comment]
you set the permission as the url without "/"
ex if you need to give him permission to view admins '/admins/all' it would be "adminsall"

**Comment by lonerunner** [comment]
Great, thanks, that is what i needed, so i added workerall and workeredit, and now that user have only access to view and edit workers.
But there is still problem with links on the menu, the limited user can still see all the links as super admin, even though they are not clickable. Is it possible to hide the links from menu too to limited user?

**Comment by hamdiwanis** [comment]
you will need to edit the main view at "yourproject\resources\views\vendor\panelViews"
maybe you could add a condition with blade's @if
