### ISSUE TITLE
Panel, Demo, and Documentation Links not working

### ISSUE THREAD

**Issue by a1iraxa** [serverfireteam/panel#259]
http://laravelpanel.com/
http://demo.serverfire.net/panel
http://laravelpanel.com/docs/master
![screenshot_2](https://cloud.githubusercontent.com/assets/15581553/17659394/a880bcde-62eb-11e6-9e31-15b7375a2ae7.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/15581553/17659395/a883a6d8-62eb-11e6-9490-9a615eef1acc.png)

**Comment by serverfire** [comment]
@a1iraxa fixed , thank you for reporting that
