### ISSUE TITLE
Tags not showing saved value

### ISSUE THREAD

**Issue by mxmtsk** [serverfireteam/panel#260]
I'm using the tags field and saving as well as the typeahead works just fine but when I load up the edit form after adding some, the textfield is empty. What can I do?

`$this->edit->add('musictypes.name','Music Types','tags');`

**Comment by mxmtsk** [comment]
solved

**Comment by Fragger5000** [comment]
@mxmtsk I've the same problem, may I ask you how did you solved?

**Comment by mxmtsk** [comment]
@Fragger5000 I solved it by adding the following in line 172:

https://www.diffchecker.com/QNqjWvAP

(I copied the original code and created a custom field to not loose the change when an update of this packages occurs :)

**Comment by Fragger5000** [comment]
Thank you, it worked also for me.
