### ISSUE TITLE
How to select multiple fields of controller ::lists with checkboxgroup?

### ISSUE THREAD

**Issue by lonerunner** [serverfireteam/panel#261]
I have two fields for first_name and last_name in one controller and database, and for another controller i am trying to pull the info with both fields in checkboxgroup.
Reading the instructions, the chekboxgroup should be added like this

```
$this->edit->add('workers','Associated Workers with this proccess','checkboxgroup')->options(\App\worker::lists('first_name', 'id')->all());
```

But since i have separated fields for first and last name of the `worker` i need to get both fields in `worker::lists`, i tried with concatenate, DB::raw and also DB::select, which usually worked but i can't get it now.

**Comment by serverfire** [comment]
you can create a array and give it to that param
