### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by undercover44** [serverfireteam/panel#263]
I have been follow all steps but i can't see admin panel.. after install when i access my domain i see default laravel template

**Comment by swaylay** [comment]
I'm having same issue;

I install on my local environment and it works properly.
I install on a remote server and I receive the same issue as @undercover44 

www.domain.com works properly;
www.domain.com/panel 404 by apache

**Comment by serverfire** [comment]
you need to active the mod rewrite in Apache
