### ISSUE TITLE
Don't use DataEdit

### ISSUE THREAD

**Issue by mxmtsk** [serverfireteam/panel#265]
I am using DateEdit for most of my data and it works fine as it's quite simple but I have one polymorphic relationship that is quite complex. As this relationship type is not supported I want to integrate my own Edit and Create Code - is it possible to use the edit method to implement my own form and save/create logic?

**Comment by serverfire** [comment]
you have two option here , 

1 . create new filed type for curd system , 

2 . not using curd for this type of controller
