### ISSUE TITLE
Class 'App\\' not found - Fatal error

### ISSUE THREAD

**Issue by moveo** [serverfireteam/panel#266]
I just installed the Panel and headed to the URL after login : http://xyz.net/panel/Role/all

Response I got : 
{"success":false,"message":"Class 'App\' not found","data":[],"debug":{"line":68,"file":"\/var\/www\/dev-imaginovation.net\/public_html\/ridealong\/apis\/vendor\/serverfireteam\/panel\/src\/controllers\/CrudController.php","class":"Symfony\Component\Debug\Exception\FatalErrorException","trace":["#0 {main}"]}}

Why Is it? Can somebody help me?

**Comment by serverfire** [comment]
are you using different namespace for panel ?
