### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Nagendra1421** [serverfireteam/panel#267]
I did exactly same till step 3 according to this this tutorial http://laravelpanel.com/docs/master/automatic-installation but when i go to steps it throws this error:

Fatal error: Uncaught ReflectionException: Class log does not exist in C:\xampp\htdocs\m4i-back-end\vendor\laravel\framework\src\Illuminate\Container\Container.php:734 Stack trace: #0 C:\xampp\htdocs\m4i-back-end\vendor\laravel\framework\src\Illuminate\Container\Container.php(734): ReflectionClass->__construct('log') #1 C:\xampp\htdocs\m4i-back-end\vendor\laravel\framework\src\Illuminate\Container\Container.php(629): Illuminate\Container\Container->build('log', Array) #2 C:\xampp\htdocs\m4i-back-end\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(697): Illuminate\Container\Container->make('log', Array) #3 C:\xampp\htdocs\m4i-back-end\vendor\laravel\framework\src\Illuminate\Container\Container.php(849): Illuminate\Foundation\Application->make('log') #4 C:\xampp\htdocs\m4i-back-end\vendor\laravel\framework\src\Illuminate\Container\Container.php(804): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter)) #5 C:\xampp\htdocs\m4i-back-end\vendor\laravel\framework\src\Illuminate\Container\C in C:\xampp\htdocs\m4i-back-end\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 734

Kindly suggest me what to do.

**Comment by serverfire** [comment]
which version of laravel you are using , your laravel missing log package
