### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by warksit** [serverfireteam/panel#269]
Your docs & demo website are down?

**Comment by serverfire** [comment]
working on it

**Comment by serverfire** [comment]
fixed

**Comment by warksit** [comment]
Thanks for getting right on that, had me worried!

**Comment by serverfire** [comment]
@warksit why worried ? there was apache error

**Comment by warksit** [comment]
Just that the package had gone away, I really like it!

**Comment by serverfire** [comment]
@warksit our company support this package and won't go away . Can you tell me where you use it ? we are working on brand new version with lot of features on it

**Comment by warksit** [comment]
I use it on a SaaS eTicketing solution for the owners to administer the tickets and meetings.

**Comment by serverfire** [comment]
@warksit that is great . let me know if you need any help on that .

**Comment by warksit** [comment]
The reason I was looking in the docs is I need to add some additional data to a pivot table. It looks like that is currently not supported out the box?

**Comment by serverfire** [comment]
@warksit we are using a package for that , you can right few line of code and rewrite the route , here : https://github.com/serverfireteam/panel/blob/master/src/controllers/ExportImportController.php#L20
