### ISSUE TITLE
Multiple attachments

### ISSUE THREAD

**Issue by petrovaliev95** [serverfireteam/panel#272]
Is there are any way to attach multiple files to one table with build in functionality ?

**Comment by serverfire** [comment]
yes , just have more than one  upload input

**Comment by petrovaliev95** [comment]
I think this isn't good practice. If i have 20 files to import, i must add 20 new columns in database table.

**Comment by serverfire** [comment]
we are using https://github.com/zofe/rapyd-laravel for crud so take a look there to see what you can do

**Comment by petrovaliev95** [comment]
There are no way to add multiple files that relates to one object.
