### ISSUE TITLE
Error in install - not allow connection

### ISSUE THREAD

**Issue by dagmar** [serverfireteam/panel#281]
Elementary OS 0.4;
laravel/framework (v5.3.18)

dagmar@cpix:/mnt/Dev/Desenvolvimento/PROJETOS/2016/painel$ sudo composer require serverfireteam/panel
[sudo] senha para dagmar: 
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
Your configuration does not allow connection to http://packagist.org. See https://getcomposer.org/doc/06-config.md#secure-http for details.
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date

  [Composer\Downloader\TransportException]  
  Your configuration does not allow connection to http://packagist.org. See https://getcomposer.org/doc/0  
  6-config.md#secure-http for details.                                                                     

require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...

dagmar@cpix:/mnt/Dev/Desenvolvimento/PROJETOS/2016/painel$

**Comment by serverfire** [comment]
you had network problem , maybe the composer site was down
