### ISSUE TITLE
Fatal error for step 4 : php artisan panel:install

### ISSUE THREAD

**Issue by sandipgp** [serverfireteam/panel#284]
F:\xampp\htdocs\laracms>php artisan panel:install

Warning: require(F:\xampp\htdocs\laracms\bootstrap/../vendor/autoload.php): fail
ed to open stream: No such file or directory in F:\xampp\htdocs\laracms\bootstra
p\autoload.php on line 17

Call Stack:
    0.0004     231144   1. {main}() F:\xampp\htdocs\laracms\artisan:0
    0.0010     234048   2. require('F:\xampp\htdocs\laracms\bootstrap\autoload.p
hp') F:\xampp\htdocs\laracms\artisan:16
HI,

I followed the steps from http://laravelpanel.com/docs/master/automatic-installation

I did steps 1,2,3 but for step 4 its giving me below error : 

Fatal error: require(): Failed opening required 'F:\xampp\htdocs\laracms\bootstr
ap/../vendor/autoload.php' (include_path='.;C:\php\pear') in F:\xampp\htdocs\lar
acms\bootstrap\autoload.php on line 17

Call Stack:
    0.0004     231144   1. {main}() F:\xampp\htdocs\laracms\artisan:0
    0.0010     234048   2. require('F:\xampp\htdocs\laracms\bootstrap\autoload.p
hp') F:\xampp\htdocs\laracms\artisan:16

**Comment by sandipgp** [comment]
Sorry somethig went wrong at my end.. now i am able to install larapanel but once i signed in after/login it gives me error: 

TokenMismatchException in VerifyCsrfToken.php line 67:

**Comment by serverfire** [comment]
something is wrong with your laravel token system
