### ISSUE TITLE
Change url of admin panel

### ISSUE THREAD

**Issue by schel4ok** [serverfireteam/panel#286]
Hi,

First thing I want to do is to change the url of admin panel 
`mysite.co/panel   ->  mysite.co/secretword`
maybe it is possible to do it in config\panel.php?

And generally after installing your package I cannot understand how it works.
I cannot find new files in my app folder, routes not changed.
Only  \app\Http\rapyd.php   but I cannot understand this file also.
Please give more documentation about how it works.

**Comment by serverfire** [comment]
right now you can not change the panel url , maybe you can add this to package and send a pull request , 

to understand the panel you can take a look at source code in GitHub , we have route controller etc in package code for each part of it
