### ISSUE TITLE
php artisan panel:crud create controller in subdirectory

### ISSUE THREAD

**Issue by schel4ok** [serverfireteam/panel#287]
Command `php artisan panel:crud gallery` creates controller and model.
But I want to keep all crud controllers in subdirectory `app\Http\Controllers\Admin`
How to do that?

**Comment by serverfire** [comment]
right now is not possible to do that , would be great to send a pull request

**Comment by vramiguez** [comment]
@schel4ok : Just go to /config/panel.php and add the following line to the return array:

`'controllers'      => '\\App\\Http\\Controllers\\Admin',`

And put your crud controllers in the folder you called Admin. 

It should work, at least with the latest version of panels.

**Comment by serverfire** [comment]
@vramiguez thank you for your help
