### ISSUE TITLE
export in excel

### ISSUE THREAD

**Issue by Fragger5000** [serverfireteam/panel#299]
I'm testing LaravelPanel in my XAMPP local enviroment, right now I'm wondering if it's necessary to have a particular php.ini configuration or to install and activate some PHP extension to run the export in excel format.

When I try to export in excel I see a blank page.

**Comment by kitsunekyo** [comment]
i would first check if your xampp install has all the requirements of laravel 5.3 fulfilled:

https://laravel.com/docs/5.3/installation

PHP >= 5.6.4
OpenSSL PHP Extension
PDO PHP Extension
Mbstring PHP Extension
Tokenizer PHP Extension
XML PHP Extension

once you have that you can debug the object that gets passed to the excel generator and see where you lose your content.

**Comment by Fragger5000** [comment]
I tried to use export in excel in a table with 1000+ records, and so I think that the white page is a problem related with the value of some php.ini parameters like post_max_size (which is 18 MB) and/or memory_limit (which is 128MB). 

I'm wondering if it's possible to select only some few records and than to export them... for example with checkboxes.

**Comment by serverfire** [comment]
@Fragger5000 adding this option would be very easy , you just need edit the view and add a checkbox and edit the route to export only checked ones , Please send a pull request for that
