### ISSUE TITLE
Create Drop Down with reference to another table

### ISSUE THREAD

**Issue by mepawan** [serverfireteam/panel#3]
Hi,

Can you please explain us how I can create drop down with reference to another crud item on add/edit crud items. Also how I can show that fields in listing page?

Like in your demo "Projects' crud item is linked with 'Company '. 

thanks,

**Comment by alenoosh** [comment]
Hi Ravendra Patel

You can use the 'options' method to pass the values from another table to
drop down fields. This method gets an array of key/values, for example if
the name of the model you want to get the values from is 'Company', you can
define your field like this :

$this->edit->add('field-name', 'label',
'select')->options(\Company::lists("name", "id"));

**Comment by serverfire** [comment]
Ravendra Patel, 

Should you need any further assistance, feel free to contact us again.

**Comment by mepawan** [comment]
Thanks guys (alenoosh & serverfire team).

I'll sure contact you when I need.

Regards,
Raavendra
