### ISSUE TITLE
version conflict

### ISSUE THREAD

**Issue by vijay-kumar-rana** [serverfireteam/panel#304]
Does this support only on laravel 5.3 or lower version too? I am working on laravel 5.2, and I am getting error. 
![15417790_1252742331459590_1679179339_o](https://cloud.githubusercontent.com/assets/7912330/20962859/26eadbee-bc93-11e6-9279-495d496490f0.png)

**Comment by serverfire** [comment]
@vijay-kumar-rana please update to last laravel version , we don't have plan to support old laravel version as we have limited resource
