### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by teeganl** [serverfireteam/panel#307]
I am using a laravel 5.3.
The below error is what appeared after i log in from the login page. 

`QueryException in Connection.php line 770:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'homestead.admins' doesn't exist (SQL: select * from `admins` where `email` = admin@change.me limit 1)`

note:
Upon installation, i faced this error as well.

  [Illuminate\Database\QueryException]
  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
   (SQL: select * from information_schema.tables where table_schema = homestead and table_name = migrations)

  [PDOException]
  SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.

C:\Users\Code\VirtualF>QueryException in Connection.php line 770:
'QueryException' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Code\VirtualF>SQLSTATE[42S02]: Base table or view not found: 1146 Table 'homestead.admins' doesn't exist (SQL: select * from `admins` where `email` = admin@change.me limit 1)QueryException in Connection.php line 770:
'SQLSTATE[42S02]:' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Code\VirtualF>SQLSTATE[42S02]: Base table or view not found: 1146 Table 'homestead.admins' doesn't exist (SQL: select * from `admins` where `email` = admin@change.me limit 1)

**Comment by serverfire** [comment]
You're MySQL server is not running, runs your MySQL and do the php artisan panel install again
