### ISSUE TITLE
 Display data which is fetched from two tables in CRUD with conditions

### ISSUE THREAD

**Issue by teeganl** [serverfireteam/panel#309]
I am new to laravel and i am still learning as I am working on a project. I need help in this.
I have referred to https://github.com/zofe/rapyd-laravel and http://laravelpanel.com/docs/master/faq but it did not help me.

Tables : vCompany, vIndustry

vCompany fields :
id , name , **industry_id**
Example : 1 , Test Private Ltd , 9

vIndustry fields :
**id** , name
Example : 1 , Hospitality

What do i have to add into my vCompanyController file to fetch an output like the below :

Company name : vCompany.name
 Industry : vIndustry.name where vCompany.industry_id equals to vIndustry.id

**Comment by serverfire** [comment]
@teeganl you need to ask zofe rapyd about that
