### ISSUE TITLE
laravel 5.1 support 

### ISSUE THREAD

**Issue by serverfire** [serverfireteam/panel#31]

**Comment by twoSeats** [comment]
:+1:

**Comment by juanp4d** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by Chrysanthos** [comment]
:thumbsup:

**Comment by serverfire** [comment]
@twoSeats  @juanp4d  @Chrysanthos 
For laravel 5.1 use this branch for now : https://github.com/serverfireteam/panel/tree/laravel5.1
Thank you
