### ISSUE TITLE
Convert value into text

### ISSUE THREAD

**Issue by vramiguez** [serverfireteam/panel#311]
Hi, I have a model called Course with a day of week as a number. However, In the grid of the Panel I would like to display the day of week as text. I'm already doing it in the filters and when adding/editing the elements with a list, where I'm telling which number correspond to which day. However, I haven't been able to do the same in the grid because in the database I'm not saving the day as text. I tried creating a function in the Course model to convert the number to text but without success. Could you help?

For a better explanation, if I have a course with day of week set as 4, I would like to see Friday in the grid instead of 4 (or as another column).

Thanks.

**Comment by serverfire** [comment]
@vramiguez we are using https://github.com/zofe/rapyd-laravel for crud part, you could check that repo for solutions, but the easy fix could be a js code that look for that value and convert it to text,

**Comment by vramiguez** [comment]
Thank you for the link!!.. I found the solution there. And just in case it helps anyone:
https://github.com/zofe/rapyd-laravel/issues/368
