### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by pararang** [serverfireteam/panel#313]
Hi, got 404 problem when try access mydomain.com/panel, but running well when access mydomain.com with laravel standar page on first install.

Ubuntu 16.04
Laravel Framework version 5.3.28.

installed with steps on this [link](http://laravelpanel.com/docs/master/manual-installation)

**Comment by serverfire** [comment]
Make sure your mode rewrite is enable

**Comment by pararang** [comment]
@serverfire my apache2's module rewrite already enabled

**Comment by serverfire** [comment]
When you get error 404 it mean request are not been sending to index.php at all, try write a route and see if it works or not.
