### ISSUE TITLE
Using Panel without the builtin login/role/dashboard functionalities.

### ISSUE THREAD

**Issue by bab55z** [serverfireteam/panel#324]
Thanks for bringing such a useful and simple package to Laravel.

Here is my issue.

I already have a custom login and role management in my laravel app (remote based store) and i would like to know if there any way to only use the crud functionalities without built in login, role management/control and dashboard ?

Thanks in advance.

**Comment by serverfire** [comment]
Yes, we are using https://github.com/zofe/rapyd-laravel for crud
