### ISSUE TITLE
Reset password email

### ISSUE THREAD

**Issue by arsenik** [serverfireteam/panel#326]
The reset password email I receive is not panelViews::resetPassword ( therefore does not have the link starting by /panel/password/reset )

There is the config ```Config::set('auth.passwords.panel',  ['provider' => 'panel','email'      => 'panelViews::resetPassword','table' => 'password_resets','expire' => 60]);``` but I am not sure email is working.

Does that work for you?
1.5.3

**Comment by arsenik** [comment]
By the way I had to extends Admin Model to add Notifiable traits.

**Comment by arsenik** [comment]
Found solution, 

Override Admin Model then override CanResetPasswordContract and ResetPassword toMail function ```->action('Reset Password', url('panel/password/reset', $this->token))``` 
``` 
namespace App;

use Illuminate\Notifications\Notifiable;
use App\Auth\AdminCanResetPassword as CanResetPasswordContract;

class Admin extends \Serverfireteam\Panel\Admin
{
    use Notifiable;
    use CanResetPasswordContract;
}
``` 

I override PanelServiceProvider to use the new Admin Model
``` 
namespace App\Providers;


class PanelServiceProvider extends \Serverfireteam\Panel\PanelServiceProvider
{
    public function boot()
    {
        parent::boot();

        \Config::set('auth.providers.panel',  ['driver'   => 'eloquent','model'   => \App\Admin::class]);

    }
}
```

**Comment by arsenik** [comment]
Let me know if that's good fix (if any) i'll try to create a PR.

**Comment by serverfire** [comment]
@arsenik thank you for the fast fix, Please send a pull request. Keep the good work
