### ISSUE TITLE
Error during composer require on laravel 5.4

### ISSUE THREAD

**Issue by andreud** [serverfireteam/panel#328]
Im installing the package on ubuntu on a fresh lararvel 5.4 install, and i get the following errors during install:
full coposer output: http://pastebin.com/nstJhSbY

$composer require serverfireteam/panel
Using version ^1.5 for serverfireteam/panel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
 
  Problem 1
    - Conclusion: don't install maatwebsite/excel v2.0.10
   - Conclusion: don't install serverfireteam/panel 1.5.1|install maatwebsite/excel v2.0.10
    - Conclusion: don't install serverfireteam/panel 1.5.2|install maatwebsite/excel v2.0.10
   - Conclusion: don't install serverfireteam/panel 1.5.3|install maatwebsite/excel v2.0.10
    - Conclusion: don't install serverfireteam/panel 1.5.0|remove symfony/css-selector v3.2.2|install maatwebsite/excel v2.0.10
   - Conclusion: don't install serverfireteam/panel 1.5.0|don't install symfony/css-selector v3.2.2|install maatwebsite/excel v2.0.10
   - Installation request for serverfireteam/panel ^1.5 -> satisfiable by serverfireteam/panel[1.5.0, 1.5.1, 1.5.2, 1.5.3].
   - serverfireteam/panel 1.5.0 requires maatwebsite/excel ~2.0.0 -> satisfiable

**Comment by serverfire** [comment]
@andreud yes we need to work on laravel 5.4, is it possible for you to send pull request for that?

**Comment by serverfire** [comment]
@andreud find the problem, please test last version it should work
