### ISSUE TITLE
Textarea showing as Redactor

### ISSUE THREAD

**Issue by softnode** [serverfireteam/panel#33]
Hi,

I came across this issue: I have a redactor instead a simple Textarea using this line of code:
$this->edit->add('answer', 'Resposta', 'textarea');

Shouldn't textarea give me only a textarea instead of the MCE editor?

**Comment by serverfire** [comment]
Hi,

Do you use `dev-master` or a specific version number?

**Comment by serverfire** [comment]
Thank you for reporting this problem , 

It is fixed in dev-master bransh ,
