### ISSUE TITLE
There are no commands defined in the "panel" namespace

### ISSUE THREAD

**Issue by cojocaru3** [serverfireteam/panel#333]
Hello,
I have done steps 1-3 from [Installation Guide](http://laravelpanel.com/docs/master/automatic-installation), But when I try to run `php artisan panel:install` I'm receiving following error:

> [Symfony\Component\Console\Exception\CommandNotFoundException]
> There are no commands defined in the "panel" namespace.

Please note that I have added the service provider, and run `composer update` as it was suggested in one ticket. I have also dumped autoload, no progress.
By the way, I'm  installing it over an existing project, (not fresh install), can this be the issue ? I don't actually think so.

> Laravel 5.4
> PHP 7.0.5

Thank you !

**Comment by serverfire** [comment]
Check if you have package provider added to your config/app
