### ISSUE TITLE
Method aliasMiddleware does not exist

### ISSUE THREAD

**Issue by magnito2** [serverfireteam/panel#334]
Just freshly installed laravel, `php artisan --version` says `5.2.45`, hope that's the latest.
Next thing was installing laravelpanel, and running `composer require serverfireteam/panel` installed it.
Whenever I add `Serverfireteam\Panel\PanelServiceProvider::class` to my `config/app.php` file, I get an error when I run `php artisan serve` or any other artisan command. Is there something am missing?
The error is method aliasMiddleware does not exist. Here is a screenshot
![error](https://cloud.githubusercontent.com/assets/16651794/24174796/ad302c9c-0ea3-11e7-996c-3e7c630a61d0.PNG)

**Comment by hostingseguro** [comment]
You need laravel 5.4 and php 5.6 as minimun -> http://laravelpanel.com/docs/master

**Comment by serverfire** [comment]
Thank you for helping @hostingseguro
