### ISSUE TITLE
Fix login "remember me"

### ISSUE THREAD

**Issue by hostingseguro** [serverfireteam/panel#339]
Hello,

The remember me option does not work correctly, I think to fix it should be changed the following in login.blade.php:

`<input name="remember" type="checkbox" value="Remember Me">`

to:

`<input name="remember" type="checkbox" value="true">`

**Comment by serverfire** [comment]
Hi, 

Can you send a pull request for that?

**Comment by hostingseguro** [comment]
Done. [https://github.com/serverfireteam/panel/pull/341](url)

**Comment by serverfire** [comment]
Thank you
