### ISSUE TITLE
The requested package serverfireteam/panel could not be found in any version

### ISSUE THREAD

**Issue by nomastickles** [serverfireteam/panel#34]
Hey there,

I can't install this ... even with "serverfireteam/panel": "1.3.*@dev" I can't install on 5.1. 

Maybe it's me. Anything I could check on my end?

also tried with:

"minimum-stability": "dev",
"prefer-stable" : true

Though I know that's not needed.

Thanks,
Thomas

**Comment by bobby-dev** [comment]
+1

**Comment by alenoosh** [comment]
@nomastickles Yes we haven't released it yet (we have edited the readme file beforehand). Right now you can install the latest version with laravel 5.1 support from 'master' branch : 

"serverfireteam/panel": "dev-master"

**Comment by alenoosh** [comment]
@nomastickles We have released it, now you can use the 1.3 tag : 

 "serverfireteam/panel": "1.3.*"
