### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::returnUrls() 

### ISSUE THREAD

**Issue by eliacimdavila** [serverfireteam/panel#346]
Hi.

I just updated to **1.6.8** version, and now, after login and redirect to dashboard, the page show me the next error:

> `ErrorException in Builder.php line 2443: Call to undefined method Illuminate\Database\Query\Builder::returnUrls() (View: /var/inetpub/tribuhhh.morwi.mx/resources/views/vendor/panelViews/dashboard.blade.php)`

In the **dashboard.blade.php** file, the only line I see with that call is **Line 15**:

`@if(is_array(\Serverfireteam\Panel\Link::returnUrls()))`

My previous version was **1.6.6**. My Laravel Framework version is **5.4.19**. All works fine before the update. 

When I ran the **composer update** command, it update some other packages. This is the complete list:

>   - Removing studio-42/elfinder (2.1.22)
>   - Installing studio-42/elfinder (2.1.23)
>     Downloading: 100%
> 
>   - Removing league/flysystem (1.0.35)
>   - Installing league/flysystem (1.0.37)
>     Downloading: 100%
> 
>   - Removing league/flysystem-cached-adapter (1.0.5)
>   - Installing league/flysystem-cached-adapter (1.0.6)
>     Downloading: 100%
> 
>   - Removing symfony/css-selector (v3.2.6)
>   - Installing symfony/css-selector (v3.2.7)
>     Loading from cache
> 
>   - Removing symfony/var-dumper (v3.2.6)
>   - Installing symfony/var-dumper (v3.2.7)
>     Downloading: 100%
> 
>   - Removing symfony/routing (v3.2.6)
>   - Installing symfony/routing (v3.2.7)
>     Loading from cache
> 
>   - Removing symfony/process (v3.2.6)
>   - Installing symfony/process (v3.2.7)
>     Downloading: 100%
> 
>   - Removing symfony/http-foundation (v3.2.6)
>   - Installing symfony/http-foundation (v3.2.7)
>     Downloading: 100%
> 
>   - Removing symfony/event-dispatcher (v3.2.6)
>   - Installing symfony/event-dispatcher (v3.2.7)
>     Downloading: 100%
> 
>   - Removing symfony/debug (v3.2.6)
>   - Installing symfony/debug (v3.2.7)
>     Downloading: 100%
> 
>   - Removing symfony/http-kernel (v3.2.6)
>   - Installing symfony/http-kernel (v3.2.7)
>     Downloading: 100%
> 
>   - Removing symfony/finder (v3.2.6)
>   - Installing symfony/finder (v3.2.7)
>     Downloading: 100%
> 
>   - Removing symfony/console (v3.2.6)
>   - Installing symfony/console (v3.2.7)
>     Downloading: 100%
> 
>   - Removing ramsey/uuid (3.5.2)
>   - Installing ramsey/uuid (3.6.1)
>     Downloading: 100%
> 
>   - Removing symfony/translation (v3.2.6)
>   - Installing symfony/translation (v3.2.7)
>     Downloading: 100%
> 
>   - Removing erusev/parsedown (1.6.1)
>   - Installing erusev/parsedown (1.6.2)
>     Downloading: 100%
> 
>   - Removing laravel/framework (v5.4.15)
>   - Installing laravel/framework (v5.4.19)
>     Downloading: 100%
> 
>   - Removing guzzlehttp/psr7 (1.4.1)
>   - Installing guzzlehttp/psr7 (1.4.2)
>     Downloading: 100%
> 
>   - Installing symfony/polyfill-util (v1.3.0)
>     Downloading: 100%
> 
>   - Installing symfony/polyfill-php56 (v1.3.0)
>     Downloading: 100%
> 
>   - Installing jeremeamia/superclosure (2.3.0)
>     Downloading: 100%
> 
>   - Removing maatwebsite/excel (2.1.10)
>   - Installing maatwebsite/excel (2.1.17)
>     Downloading: 100%
> 
>   - Removing serverfireteam/panel (1.6.6)
>   - Installing serverfireteam/panel (1.6.8)
>     Downloading: 100%
> 
>   - Removing tymon/jwt-auth (0.5.10)
>   - Installing tymon/jwt-auth (0.5.11)
>     Downloading: 100%
> 
>   - Removing symfony/yaml (v3.2.6)
>   - Installing symfony/yaml (v3.2.7)
>     Downloading: 100%
> 
>   - Removing phpunit/php-code-coverage (4.0.7)
>   - Installing phpunit/php-code-coverage (4.0.8)
>     Downloading: 100%
> 
>   - Removing myclabs/deep-copy (1.6.0)
>   - Installing myclabs/deep-copy (1.6.1)
>     Downloading: 100%
> 
>   - Removing phpunit/phpunit (5.7.16)
>   - Installing phpunit/phpunit (5.7.19)
>     Downloading: 100%
> 
>   - Removing psy/psysh (v0.8.2)
>   - Installing psy/psysh (v0.8.3)
>     Downloading: 100%

It could be a incompatibility with some other update?

Thanks for your help.

**Comment by serverfire** [comment]
@eliacimdavila you need to re-publish your assets to get updated view for panel
