### ISSUE TITLE
am i supposed to get all fields from my .env database setting of a table - CRUD

### ISSUE THREAD

**Issue by larrydalaw** [serverfireteam/panel#350]
i have a mysql table as below: 
```CREATE` TABLE `srFood` (
  `sid` varchar(40) NOT NULL,
  `theversion` int(10) NOT NULL,
  `create_ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` varchar(50) DEFAULT NULL,
  `update_ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` varchar(50) DEFAULT NULL,
  `delete_ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_by` varchar(50) DEFAULT NULL,
  `name_food` varchar(255) DEFAULT NULL,
  `seller_food` varchar(40) DEFAULT NULL,
  `list_cost_food` double DEFAULT NULL,
  `cname_food` varchar(100) DEFAULT NULL,
  `remarks_food` varchar(255) DEFAULT NULL,
  `packaged_quantity` int(17) DEFAULT NULL,
  `packaged_unit` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`sid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;```

and i ran this line 
php artisan panel:crud SrFood

am i supposed to link the db created table to crud and related files ? thanks.

**Comment by serverfire** [comment]
this command will create the files you need and you need to edit them to work with your table
