### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::notify()

### ISSUE THREAD

**Issue by panoslykos** [serverfireteam/panel#352]
Trying to do a password remind, i have set up email using mandril, I have laravel 5.3 with larapanel ^1.5. When i add my email and click Send Reminder I get : 
Call to undefined method Illuminate\Database\Query\Builder::notify()

While my user model already uses notifiable.

**Comment by serverfire** [comment]
We have tested this and worked with gmail
