### ISSUE TITLE
no css file is added!

### ISSUE THREAD

**Issue by devmaghari** [serverfireteam/panel#354]
hi. i've done the starting steps. but as a open the panel(login or panel page), i have no css for these pages! they are just empty html pages. also there is no image for example an empty image tag in login page referes to:

 src="http://localhost:8000/"

which is sth like this:

<div class="logo-holder">
             <img src="http://localhost:8000/">
 </div>

what is the problem with addressing ?

**Comment by mhuijser** [comment]
I have the same problem. I guess you need to build the css/js by yourself, but it's not described how to do that.

**Comment by pogocki** [comment]
Copy all files from https://github.com/serverfireteam/panel/tree/master/public to your public\packages\serverfireteam\panel\ folder.
It should work

**Comment by devmaghari** [comment]
hi, i solved my problem by getting this version of panel instead of last one: 
 "serverfireteam/panel": "1.6.7"

**Comment by serverfire** [comment]
fixed that problem, check 1.6.9
