### ISSUE TITLE
get current admin

### ISSUE THREAD

**Issue by devmaghari** [serverfireteam/panel#356]
hi. 
in my project i have a Post Model which contains (admin_id, title and body)
I have  more than one admins, so i want to know which admin has posted the Post, and also in dashboard panel i want to show the admin just the posts which he has posted(not others posts)

what should I do?

-how to get current admin id?
-how should i set parameters like admin_id to Post before saving it?
-how should i add a rule to Grid to show just admins own posts, not others?

thankd

**Comment by devmaghari** [comment]
for the second question i got that if i want to set some rules befor saving i have to do sth like this in Controller 'edit' function:

 parent::edit($entity);
        \App\Posts::creating(function($data) {
            $data->admin_id = '1';
        });

but still i dont know how to get current admin!

**Comment by serverfire** [comment]
You could use : \Auth::guard('panel')->user()
