### ISSUE TITLE
Create Crud

### ISSUE THREAD

**Issue by rodrigoweber** [serverfireteam/panel#36]
Hi,
i'm trying generate crud using commands but it generate this:
> <?php namespace {{namespace}};

>use Illuminate\Database\Eloquent\Model;

>class {{class}} extends Model {

  >  protected $table = '{{class}}';

>}

the namespace not create with correct name, right? How  fix it?

thanks

**Comment by serverfire** [comment]
It is fixed and pushed in master branch , later @alenoosh  will release new version
