### ISSUE TITLE
Error in panel:install

### ISSUE THREAD

**Issue by arucuenca** [serverfireteam/panel#366]
When I run

> php artisan panel:install

I get this error message:

>   [ReflectionException]                                                       
>   Method Serverfireteam\Panel\Commands\PanelCommand::handle() does not exist

I'm using Laravel 5.5.13 and panel 1.6

**Comment by serverfire** [comment]
Please install from master branch for laravel 5.5

**Comment by arucuenca** [comment]
Thanks! Worked perfectly!
