### ISSUE TITLE
Illuminate \ Database \ QueryException (42S22) SQLSTATE[42S22]: Column not found: 1054 Unknown column 'email' in 'where clause' (SQL: select * from `admins` where `email` = admin@change.me limit 1)

### ISSUE THREAD

**Issue by nikay05** [serverfireteam/panel#367]
can i know how to solve this problem.. i am a newbie to laravel. thanks in advance.

Illuminate \ Database \ QueryException (42S22) SQLSTATE[42S22]: Column not found: 1054 Unknown column 'email' in 'where clause' (SQL: select * from `admins` where `email` = admin@change.me limit 1) #367

**Comment by serverfire** [comment]
It can not find email column in your admin table.

Did you have the admin table before installing the panel?

**Comment by nikay05** [comment]
yes i do.. i have the table and the columns but the problem now is that i cannot login to the dashboard.. it says invalid username or password... i inputted correct data..what is wrong?

**Comment by serverfire** [comment]
please remove the admin table and create that with migration
