### ISSUE TITLE
Unknown column 'firstname' in 'where clause'

### ISSUE THREAD

**Issue by kategarshyna** [serverfireteam/panel#372]
This error appears when searching in admins list by First Name
Error: http://take.ms/anBI3

Probably in your AdminController "all" action (http://take.ms/Uzyye) should be "first_name" except "firstname"

**Comment by AdrianHL** [comment]
Got the same issue. I'm going to submit now a PR that fix this error.

**Comment by AdrianHL** [comment]
Fix has been merged so this issue could be solved once included in a newer version.
