### ISSUE TITLE
NotFoundHttpException in Controller.php line 269:

### ISSUE THREAD

**Issue by sebasmercado** [serverfireteam/panel#39]
Hi! I followed your tutorian on Laravel 5.1. I have a working site build here and then I added the required as mentioned in the tutorial. No errors during installantion, but after I installed it, I tried to go to mysite.com/public/admin and got this error:

What could be going wrong?

Thanks in advance!

Sebas.

**Comment by serverfire** [comment]
You should go to mysite.com/public/panel not mysite.com/public/admin . That would work .

Other thing for your security  , you should not upload all your project file in www , just public folder in www other folder of laravel should be in upper folder

**Comment by sebasmercado** [comment]
Hi! Thanks a lot for your answer! I actually tried with these:

1. mysite.com/public/admin
2. mysite.com/public/panel
3. mysite.com/admin

Always got the same error message. Sorry I am quite new at Laravel 5, and I can't figure out how the routes in the package could become active in the main project's routes. I mean, in my main project I already have a routes.php and I see another routes.php inside your package. Obviously my instantiation of laravel can't figure out the routes in the package, but not sure why.

Thanks a lot for your time and assistance!

Sebas.

**Comment by serverfire** [comment]
Okay that is different .

1. Did you install the laravel panel with php artisan panel:install ?
2. Did you add panel provider to your app.php in cofing folder ?

**Comment by sebasmercado** [comment]
Hi! Thanks for your time!

In the end, I was able to make it work, it was a combination of two things:

1. Under apache, I had my vhost config file pointing directly to mysite.com/public/, this I wanted to keep that way.
2. In my site's routes.php file, I had 
```php 
Route::controller('/', HomeController); 
``` 
This generated routes with up to 5 parameters. By issuing php artisan route:list, one of the routes was something like '/index/{param1?}{param2?}{param3}'. I fixed it by using:
```php
Route::get('/', 'HomeController@getIndex');
Route::post('/', 'HomeController@postIndex');
```
A combination of both had the panel finally working. I don't know if that is relevant for your documentation, but I mention this just in case. Maybe if you had a smarter setup for the main site routes.php file, it would be nice if you could share it.

Thanks again for your time and great work in the panel!!!

Sebas.

**Comment by serverfire** [comment]
We do have this in mind to have composer commend to create full laravel project with panel just with one commend .

Should you have any other concerns, feel free to contact us back.
Thank you .

**Comment by sebasmercado** [comment]
Awesome sounds great. Looking forward to it! Cheers and kepp up the good work!
