### ISSUE TITLE
Help about  'created_at' and 'updated_at' field 

### ISSUE THREAD

**Issue by mepawan** [serverfireteam/panel#4]
Hi,
Is there compulsory ot have 'created_at' and 'updated_at' field in crud item table?

because I have added 'Languages' in crud item and in languages table there is id, name, code. So it throws error that unknown columng 'updated_at'

Can you please guide me?

Thanks,

**Comment by siavash13** [comment]
Hi,
no it's not compulsory just add this to your model
   ` public $timestamps = false;`

**Comment by mepawan** [comment]
It works. Thank you so much 'siavash12'
