### ISSUE TITLE
Storing secure passwords

### ISSUE THREAD

**Issue by sebasmercado** [serverfireteam/panel#46]
Hi! I am trying to store a password with an encription. How can I do that?
Also, I would like to preprocess some data before storing it. What would be the suggested way of doing it? 

Thanks!

Sebas.

**Comment by serverfire** [comment]
@sebasmercado you should use model event for that .
for password you can use creating 

```php
	public function edit($entity) {
        parent::edit($entity);
        \App\Modelname::creating(function($data) {
		$data->password = Hash::make(\Request::input('password'));
	});
	$this->edit = \DataEdit::source(new Modelname());

	$this->edit->label('Edit User');

	$this->edit->add('password', 'Password', 'text');
	return $this->returnEditView();

```
@alenoosh  please add this to doucment , thank you

**Comment by sebasmercado** [comment]
Excellent! Thanks!
