### ISSUE TITLE
Colorpicker aid does not work?

### ISSUE THREAD

**Issue by jedidas** [serverfireteam/panel#49]
Hi, I'm using the colorpicker in a register.
The widget is loaded on the site and is run but not displayed.
I tried to show it but I could not.

Here a sample image

[Image preview](http://s11.postimg.org/vrl53i7k3/color.jpg)

Please help.

**Comment by serverfire** [comment]
@jedidas  in last version of laravelPanel it working .
Could tell me which version of laravelpanel you are using ?

Maybe it is bootstrap colorpicker bug .

You could download last version from here : http://mjolnic.com/bootstrap-colorpicker/ and put it public folder ( public\packages\zofe\rapyd\assets\colorpicker ) see it fix that
