### ISSUE TITLE
Create multiple image thumbs for a picture?

### ISSUE THREAD

**Issue by jedidas** [serverfireteam/panel#50]
Hello, I wanted to know is possible to upload an image to create the image in various sizes and stored in different directories all with the same name?

```php
$image = $this->edit->add('image', 'Imagen Category', 'image');
$image2 clone $image;

$image->resize(600, 300)->move('uploads/category/')->preview(200, 100);
$image2->resize(300, 150)->move('uploads/category/small')->preview(100, 50);
```

I tried but just make me a picture

Thank you very much

**Comment by serverfire** [comment]
@jedidas you have few options here 

1. create new filed type for rapyd ( https://github.com/zofe/rapyd-laravel/wiki/Creating-Fields )
2. listen to created to  create other image from uploaded one 
3. resize when user request the image .
