### ISSUE TITLE
Multilingual models?.

### ISSUE THREAD

**Issue by jedidas** [serverfireteam/panel#52]
Hello, thank you very much for all your help.
It is possible to use models with laravelpanel ads, he occupied create a manageable site in two languages.
You must add a package or enable config option?

**Comment by alenoosh** [comment]
@jedidas I'm not sure if I understood what you mean exactly but if you want to change the default language, you can set the 'locale' option in config/app.php.

**Comment by jedidas** [comment]
Sorry, my English is very poor.
In my project the products are in various languages.
As I can add multi languages in the models?

You can add a packege like this: https://github.com/dimsav/laravel-translatable?

**Comment by alenoosh** [comment]
@jedidas I reviewed the 'laravel-translatable' package, it seems a good package, you can add this package in composer.json of panel and test it. Please let us know about the results. Thanks
