### ISSUE TITLE
Error 404 when accessing in the browser

### ISSUE THREAD

**Issue by chesstrian** [serverfireteam/panel#53]
Hi,

I'm starting using laravel and panel and I have followed steps several times, but when I go to the browser, everything works for http://localhost/app, but not for http://localhost/app/panel.

Any idea why is this happening?, I saw the steps in the video, but still can't make this work.

Thanks in advance.

**Comment by alenoosh** [comment]
@chesstrian What is the error ? Also check your logs in storage/logs folder.

**Comment by chesstrian** [comment]
It's an apache related configuration, in apache2.conf file I changed `AllowOverride None` to `AllowOverride All` for `/var/www` directory setup.

Thanks.
