### ISSUE TITLE
There's a - in the html

### ISSUE THREAD

**Issue by RichardLindhout** [serverfireteam/panel#58]
This is a very little issue but maybe the - should be removed.

In the panelViews > mainTemplate.blade.php

-                              {{--*/ $links  = \Serverfireteam\Panel\Link::all(); /*--}}

                               @foreach($links as $key => $value )

The - on the beginning should be removed?

**Comment by alenoosh** [comment]
@RichardLindhout Thanks for reporting. Yes it is an extra character, I have removed it.
