### ISSUE TITLE
Release demo models and controllers

### ISSUE THREAD

**Issue by RichardLindhout** [serverfireteam/panel#59]
Maybe we can learn from it, because it's a little hard to understand how it works.

I just found the linkController.php so now i understand a little bit more how it works!

Amazing panel dudes! Keep the good work up!

**Comment by alenoosh** [comment]
@RichardLindhout You can check the code of demo from https://github.com/laravelpanel/demo

**Comment by RichardLindhout** [comment]
Thanks :+1: ! Maybe add a link on the readme (Demo section), so people know it's there :)
