### ISSUE TITLE
Class 'Category' not found

### ISSUE THREAD

**Issue by Globax** [serverfireteam/panel#61]
Hi,
class CategoryController extends CrudController{

    public function all($entity){
        parent::all($entity);

        $this->grid = \DataGrid::source("categories");
        $this->grid->add('id','ID', true)->style("width:100px");
        $this->addStylesToGrid();
                 
        return $this->returnView();
    }
    
    public function edit($entity){
        
        parent::edit($entity);

        $this->edit = \DataEdit::source(new \Category());

        $this->edit->label('Edit Category');
        $this->edit->add('name','Name', 'text')->rule('required|min:5');
        $this->edit->add('description','description', 'text')->rule('required|min:5');

        return $this->returnEditView();
    }    
}

I have this error: Class 'Category' not found

i have CategoryController controller, Category model

**Comment by alenoosh** [comment]
@Globax You should write the complete namespace for name of model (for example : \App\Category) or you should add the 'use \App\Category;' line at the beginning of the file and write just the model name (for example: Category).
