### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by Globax** [serverfireteam/panel#63]
Hi,
I have some problem with languages administation. //Sorry for bad english

I have Languages menu (Language model, LanguageControllel), i can add, edit and delete languages. For example i was added English and Russian languages.
And i have Categories menu (Category model, CategoryController), when i add new category, i have Select box with two added languages, and seven text boxes. I need add Categories with this two languages, how can i do that? Considering also that later it will be added to another languages.

**Comment by serverfire** [comment]
@Globax  if i understand you , you want select more than one languages per category .

You could use this method :

checkboxgroup (checkbox list), usually using relation.fieldname to store values in a pivot table, for a belongsTo relation

```php
$this->edit->add('language', 'Language ', 'checkboxgroup')
 ->options(Language ::lists("name", "language_id"));
```

Please check documents for any type of filed you need : http://laravelpanel.com/docs/master/crud-fields

Feel free to ask any questions 

Thank you

**Comment by Globax** [comment]
@serverfire No, that's not what I need.

There is added two languages: http://prntscr.com/7vzf6n

And the is my Options view example:
http://prntscr.com/7vzgjl //there are 2 records for one Option and each is in different language
http://prntscr.com/7vzgvr

I need, 1 record, wich view will be like that: http://prntscr.com/7vzisj

And when i Add or Edit, i will can add different record for each language, like that:
http://prntscr.com/7vzhvd
http://prntscr.com/7vzi3h

**Comment by serverfire** [comment]
@Globax  I'm not sure what you need, 

But if you want to only show keyword in list of record and  you don't need show language you could just remove lang filed from grid and only use it in edit section .

**Comment by Globax** [comment]
@serverfire 
I have this: https://sendvid.com/e5vyubn3
When i Edit, i edited only language id, i need different Name for Each language. When i change Language, i need load an appropriate name for selected Language.

I need this: https://sendvid.com/qaet4nq2

**Comment by serverfire** [comment]
@Globax I did not get what you need yet , If you could explain it other way

**Comment by Globax** [comment]
@serverfire i create own CRUD function.. and here is how does it work https://sendvid.com/w62ckok8

**Comment by serverfire** [comment]
@Globax  Very good job , If you create pull request we could add for others .

Thank you
