### ISSUE TITLE
panel de control en laravel

### ISSUE THREAD

**Issue by felipehernandezvega** [serverfireteam/panel#65]
hola quiero notificar que estoy usando laravel 5.0 y quiero poder hacer uso de este producto pero al momento de indicar en app.php lo que indican y luego intentar instalar desde la consola me lanza un error fatal y no he encontrado solución podrían decirme si algo estoy realizando mal por favor

**Comment by torresomar** [comment]
@felipehernandezvega hola, primero que nada intenta que tu respuesta sea en ingles, de lo contrario veo muy dificil que te contesten personas que han tenido un problema similar al tuyo. Si puedes poner el stacktrace que te dio al momento de instalar puedes dar una mejor idea de que es lo que sucede con la instalacion.

**Comment by serverfire** [comment]
@torresomar  Thank you
