### ISSUE TITLE
How Do I Add A Table To View,Edit,Add Users ?

### ISSUE THREAD

**Issue by philnind** [serverfireteam/panel#66]
The documentation is very poor and I cannot work out how to add the neccessary parts to view,add and edit users ?

**Comment by serverfire** [comment]
@philnind  
Thank you for using laravelpanel .
If you want manage admins for panel , you have to create crud controller and model for admin table .
something like this : https://github.com/serverfireteam/panel/blob/user_roles/src/controllers/UsersController.php

we are working for users management . you could use the alpha version of users management from user_roles branch.

Thank you

**Comment by philnind** [comment]
Are these in a different location from the normal front end models and controllers? 

Sent from myMail for iOS


Sunday, 26 July 2015 09:29 +0100 from Serverfire  <notifications@github.com>:

**Comment by serverfire** [comment]
@philnind you could just put them in app\Http\Controllers
