### ISSUE TITLE
Create images Gallery

### ISSUE THREAD

**Issue by Globax** [serverfireteam/panel#68]
Hi,
How i can create something like Gallery?

I when add new Gallery, i need one textbox for Gallery name, and by default one Image field, but pressed on Add or + Button, will appear new Image field. Also need limit, for example max 30 images per Gallery.

**Comment by serverfire** [comment]
@Globax  

You have to create custom field for that , here the document :

http://laravelpanel.com/docs/master/crud-custom-fields

**Comment by Globax** [comment]
@serverfire 
I've studied the documents, but still do not understand how to build own Custom field. Can you give some Custom field example that corresponds to what I need? And how can it be made to the image names stored in Array like JSON and store inside the Database?

**Comment by serverfire** [comment]
@Globax  you could do something like tag : https://github.com/zofe/rapyd-laravel/blob/master/src/DataForm/Field/Tags.php
