### ISSUE TITLE
Create subselect

### ISSUE THREAD

**Issue by Globax** [serverfireteam/panel#69]
Hi,
I have one Select with two options: text and select

How i can create that when i select Text, below Select will apper Textbox, but if i select Select, below Select will apper new Select (subselect) with "Add more" button, by clicked on "Add more" button, will apper new Subselect.

Thanks!

**Comment by serverfire** [comment]
@Globax 

Thank you for using laravelpanel , for that you have to create custom fields , here document of how create custom fields :

http://laravelpanel.com/docs/master/crud-custom-fields

**Comment by Globax** [comment]
@serverfire 
I've studied the documents, but still do not understand how to build own Custom field. Can you give some Custom field example that corresponds to what I need? And how can it be made to the Selected values stored in Array like JSON and store inside the Database?

**Comment by serverfire** [comment]
Take loot at this one : 
https://github.com/zofe/rapyd-laravel/blob/master/src/DataForm/Field/Redactor.php

You have do to something like this , add javascript to handle and save json format

**Comment by Globax** [comment]
@serverfire 
I found this: http://www.rapyd.com/rapyd-demo/edit

It is possible to combine this with laravel panel? Last fiels Categories is that what i can use insted Subselect.

**Comment by serverfire** [comment]
@Globax  yes , we are using rapyd for crud

**Comment by Globax** [comment]
@serverfire Tnx!
