### ISSUE TITLE
Class CreateModelCommand not found

### ISSUE THREAD

**Issue by daverdalas** [serverfireteam/panel#7]
Hi,
I downloaded your repository for Laravel 5. The installation was successful but when I typed php artistan panel:install I got this error:
![image](https://cloud.githubusercontent.com/assets/5399813/6647672/3a5f135e-c9d1-11e4-8ccf-42b96924bf1f.png)
Adding the prefix Commands\ to class names solve the problem.

**Comment by alenoosh** [comment]
Please make sure you are getting the latest changes from 'master'  branch
of our package.

**Comment by serverfire** [comment]
@daverdalas I have check the problem and it did fixed , please if you did face the problem , report it here
