### ISSUE TITLE
Two tables in one Menu/Controller

### ISSUE THREAD

**Issue by Globax** [serverfireteam/panel#70]
Hi,
I have create Contacts menu, ContactController and Contact model. 
I can Add, Edit and Delete Contacts.

How can i add new Table bellow Contacts table, with one record which i can only Edit (without Add and Delete option).

Thanks!

**Comment by serverfire** [comment]
@Globax  

We have plan to add this options , for know you can just hide that buttons , like this : 
```php
		$html = $this->returnView();

		$html .= '<style>.table td:last-child,.table th:last-child, a.btn.btn-primary {display:none}</style>';

        return $html;
```

**Comment by Globax** [comment]
@serverfire 
This is very useful, thank you!
