### ISSUE TITLE
How works lists() function?

### ISSUE THREAD

**Issue by Globax** [serverfireteam/panel#71]
Hi,
http://laravelpanel.com/docs/master/crud-fields - select box - \App\Company::lists("name", "id"). Not working for me: https://sendvid.com/57ckzx2n

**Comment by serverfire** [comment]
@Globax  you have to pass a array of record to select box , list function do that , take a look at http://laravel.com/docs/5.1/queries

**Comment by Globax** [comment]
@serverfire 
Clear, I think that it has a specific function, I created my own and everything works.

Tnx!
