### ISSUE TITLE
CRUD Fields tags not working

### ISSUE THREAD

**Issue by Globax** [serverfireteam/panel#72]
Hi,
CRUD Fields (http://laravelpanel.com/docs/master/crud-fields) tags not working for me https://sendvid.com/4e7zwmm7

**Comment by serverfire** [comment]
@Globax  i have done some test and it work for me , make sure your models have belongsTo

**Comment by Globax** [comment]
@serverfire 
Have no idea what is wrong https://sendvid.com/2sp0rfp4

**Comment by serverfire** [comment]
@Globax  if it is possible for you , share the code with me info[[@]]serverfire.net , i will check that for you
