### ISSUE TITLE
Translation is disable for rapyd-laravel in the laravel5.1

### ISSUE THREAD

**Issue by aoslee** [serverfireteam/panel#77]
Translation is disable for rapyd-laravel but is ok for panel in the laravel5.1.
I do this for following steps:
1.config/app.php modify 'locale' => 'zh-CN'
2.add resources\lang\vendor\panel\zh-CN\fields.php and modify fields.php
3.add resources\lang\vendor\rapyd-laravel\zh-CN\rapyd.php and modify rapyd.php

  Login in panel and the  panel is translated,but rapyd-laravel is not translated.
What did I do wrongs?
                                                     regards

**Comment by alenoosh** [comment]
@aoslee Would you please send me your translated files ?

**Comment by aoslee** [comment]
@alenoosh: hi!
     I don't khow how send the files in the github,So Copy the content to here.

<?php

return array(
    'save'    => '保存',
    'undo'    => '回退',
    'show'    => '显示',
    'modify'  => '编辑',
    'delete'  => '删除',
    'add'     => '添加',
    'reset'   => '重置',
    'search'  => '查询',
    'back'    => '返回',

    //dataedit
    'inserted'   => '新记录创建完成.',
    'updated'    => '记录已经更新.',
    'deleted'    => '记录已经删除.',
    'err'        => '读错误.',
    'err_unknown'=> '没有选择记录',
    'err_dup_pk' => '主键冲突',
    'conf_delete'=> '确定删除?',
    'empty_list' => '未添加记录!'
);

**Comment by alenoosh** [comment]
@aoslee Change the name of 'rapyd-laravel' folder to 'rapyd' and it will work.

**Comment by aoslee** [comment]
@alenoosh:  Hi.
 Everything is ok but  'search' and 'reset' and  'Add' and 'Edit' are not translated in the 'panel\entity\all' page.
regards.

**Comment by alenoosh** [comment]
@aoslee The 'Add' and 'Edit' buttons were not translated, I have fixed this so please get the latest update.
But about the 'search' and 'reset' buttons, they are defined in the code of your crud, so you should translate them by using the 'trans' method of laravel.

**Comment by aoslee** [comment]
@alenoosh :+1: 
Thanks a lot .Everything is  ok.

regards
