### ISSUE TITLE
Own Route Auth

### ISSUE THREAD

**Issue by Globax** [serverfireteam/panel#78]
Hello,
I had made my own CRUD and Routes, when Session is ended it shows an error. http://sendvid.com/jjiykmrz

How can i create own Redirect to /panel/login when Session is ended?

**Comment by serverfire** [comment]
@Globax  You are getting error from something else , fix that and you will redirect to login page

**Comment by Globax** [comment]
@serverfire Hmm, but when i Log in, everything works perfectly.

**Comment by serverfire** [comment]
@Globax If you have re-write the route you should protect the rout with auth 
```
Route::group(array('prefix' => 'panel', 'before' => 'auth'), function()....
```

**Comment by Globax** [comment]
@serverfire I put this 
Route::get('panel/SquareBlock', array('uses' => 'App\Http\Controllers\SquareBlockController@index'));
in Route::group(array('prefix' => 'panel', 'before' => 'auth'), function()... in your route.php file, i have this error MethodNotAllowedHttpException in RouteCollection.php line 201:

**Comment by serverfire** [comment]
@Globax  please put all the code you have in route

**Comment by Globax** [comment]
@serverfire 
<?php

if (\Request::is('panel*'))
{
	\Config::set('auth.model', 'Serverfireteam\Panel\Admin');
    \Route::filter('auth', function(){
       		if (\Auth::guest()) {
            		if (\Session::has('message')) {
				        $message = \Session::get('message');
            		} else {
				        $message = \Lang::get('panel::fields.enterEmail');
            		}
            		return \Redirect::to('/panel/login')->with('message', $message)->with('mesType', 'message');
		    }
	});
}

Route::group(array('prefix' => 'panel', 'before' => 'auth'), function()
{
	// main page for the admin section (app/views/admin/dashboard.blade.php)
	Route::get('/', function(){
        $version = '';
        try
        {
            $composer_lock = json_decode(File::get(base_path().'/composer.lock'),true);
            foreach($composer_lock['packages'] as $key=>$value){
                if($value['name'] =="serverfireteam/panel")
                    $version =  $value['version'];
            }
        }
        catch (Exception $exception)
        {
            \Log::warning("I can't found composer.lock for laravelpanel ");
        }

        return View::make('panelViews::dashboard')->with('version', $version);
    });

    Route::any('/{entity}/export/{type}', array('uses' => 'Serverfireteam\Panel\ExportImportController@export'));
    Route::post('/{entity}/import', array('uses' => 'Serverfireteam\Panel\ExportImportController@import'));
    Route::any('/{entity}/{methods}', array('uses' => 'Serverfireteam\Panel\MainController@entityUrl'));
    Route::post('/edit', array('uses' => 'Serverfireteam\Panel\ProfileController@postEdit'));
    Route::get('/edit', array('uses' => 'Serverfireteam\Panel\ProfileController@getEdit'));


    Route::get('/changePassword', array('uses' => 'Serverfireteam\Panel\RemindersController@getChangePassword'));

    Route::post('/changePassword', array('uses' => 'Serverfireteam\Panel\RemindersController@postChangePassword'));

    Route::get('panel/SquareBlock', array('uses' => 'App\Http\Controllers\SquareBlockController@index'));
});


Route::post('/panel/login', array('uses' => 'Serverfireteam\Panel\AuthController@postLogin'));

Route::get('/panel/password/reset/{token}', function ($token){
    return View::make('panelViews::passwordReset')->with('token', $token);
});



Route::get('/panel/logout', array('uses' => 'Serverfireteam\Panel\AuthController@doLogout'));

Route::post('/panel/reset', array('uses' => 'Serverfireteam\Panel\RemindersController@postReset'));

Route::get('/panel/reset', array('uses' => 'Serverfireteam\Panel\RemindersController@getReset'));

Route::get('/panel/remind',  array('uses' => 'Serverfireteam\Panel\RemindersController@getRemind'));

Route::post('/panel/remind', array('uses' => 'Serverfireteam\Panel\RemindersController@postRemind'));


Route::get('/panel/login',  array('uses' => 'Serverfireteam\Panel\AuthController@getLogin'));

**Comment by alenoosh** [comment]
@Globax There is something wrong in the definition of 'SquareBlock' route. You are defining this route under 'panel' route group and again you are adding the 'panel' prefix before this route : 

Route::group(array('prefix' => 'panel', 'before' => 'auth'), function()
{
  .
 Route::get('panel/SquareBlock', array('uses' => 'App\Http\Controllers\SquareBlockController@index'));
  .
 });

It should be like this : 

 Route::get('SquareBlock', array('uses' => 'App\Http\Controllers\SquareBlockController@index'));

**Comment by Globax** [comment]
@alenoosh 
Yeah, now it works perfectly.

Big tnx from me.

**Comment by alenoosh** [comment]
@Globax You're welcome
