### ISSUE TITLE
Mozilla Firefox - Logout $ Setting style bug

### ISSUE THREAD

**Issue by Globax** [serverfireteam/panel#79]
http://prntscr.com/862q2c

**Comment by alenoosh** [comment]
@Globax The bug is fixed. Please update to the latest version.

**Comment by Globax** [comment]
@alenoosh Bug still there: http://prntscr.com/86sf5r

**Comment by alenoosh** [comment]
@Globax Please make sure that : 
1) You have updated to the latest version.
2) The latest version of views and assets of panel are published.

**Comment by Globax** [comment]
@alenoosh 
1) done with composer update
2) how can i do that?

**Comment by alenoosh** [comment]
@Globax Just run 'php artisan panel:install' in the root folder of your app : 

/home/your-user/your-app$ php artisan panel:install

**Comment by Globax** [comment]
@alenoosh All my modifications in your panel file will deleted?

**Comment by alenoosh** [comment]
@Globax If you have made modifications, make a copy of them.

**Comment by Globax** [comment]
@alenoosh Bug is still there..

**Comment by alenoosh** [comment]
@Globax The new files are not published, so please make a backup of your files and then run the following command to force replacing the new files : 

php artisan vendor:publish --force

**Comment by Globax** [comment]
@alenoosh Yeah, now it looks better :) Tnx :)
