### ISSUE TITLE
"RESET" Button is Error

### ISSUE THREAD

**Issue by aoslee** [serverfireteam/panel#81]
Hi:
   RESET button is error at the filter and Its adress  likes 'http://***.***.**.**/laravel/public/laravel/public/panel/Link/all'.My web server is apache.

regards.

**Comment by alenoosh** [comment]
@aoslee Would you please print the error you are getting ?

**Comment by aoslee** [comment]
@alenoosh : hi.
Reset's adress is error because '/laravel/public' is twice writed.
Error messages:
Sorry, the page you are looking for could not be found.
1/1 NotFoundHttpException in RouteCollection.php line 143:.

regards

**Comment by alenoosh** [comment]
@aoslee You should correct the link of your app, actually you should create the link from the public folder  of your app. So for example the link of 'Link' crud should look like this : 

http://localhost/laravel/panel/Link/all

And also make sure to set the 'url' of your app in your config file ('url' option).

**Comment by aoslee** [comment]
@alenoosh :
I don't know what be modified. This error  disappears after i update latest version.
Thanks a lot and I will close this.
regards
