### ISSUE TITLE
Not updated Delete button bugfix

### ISSUE THREAD

**Issue by Globax** [serverfireteam/panel#82]
https://github.com/serverfireteam/panel/issues/67

change css file : public\packages\serverfireteam\panel\css\styles.css

line 7794 (now it is line 7800)

/*-------------- zofe rapyd => crud --------------------*/
.table a {
  text-decoration: none;
  transition: all ease 250ms;
}
.table a:hover {
  transform: scale(1.2, 1.2);
  -webkit-transform: scale(1.2, 1.2);
}
.table .icomoon {
  font-size: 22px;
  text-decoration: none;
  transition: all  ease 250ms;
}
.table tr {
  transition: all ease  250ms;
}
.table tr:nth-child(even) {
  background: #f5f5f5;
}
.table tr:hover {
  border-color: #777;
}
.btn {
  transition: all ease 250ms;
}
too :

/*-------------- zofe rapyd => crud --------------------*/
.table a {
  text-decoration: none;
}
.table .icomoon {
  font-size: 22px;
  text-decoration: none;
}
.table tr:nth-child(even) {
  background: #f5f5f5;
}
.table tr:hover {
  border-color: #777;
}

**Comment by alenoosh** [comment]
@Globax It is updated now.
