### ISSUE TITLE
artisan panel:anycommand doesn't work

### ISSUE THREAD

**Issue by thedangler** [serverfireteam/panel#84]
I get errors when I try to use the commands. using laravel5.1

Catchable fatal error: Argument 2 passed to Illuminate\Routing\UrlGenerator::__construct() must be an instance of Illuminate\Http\Request, null given, called in /home/vagrant/Projects/dentalEd/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php on line 64 and defined in /home/vagrant/Projects/dentalEd/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php on line 99

**Comment by rafaelsisweb** [comment]
Here same problem after run panel:install, Laravel broke.

**Comment by alenoosh** [comment]
@thedangler The bug is fixed.
