### ISSUE TITLE
How to list my app models?

### ISSUE THREAD

**Issue by hopewise** [serverfireteam/panel#87]
I just installed the panel into my existing app, but I don't know how to include my app models into the dashboard of panel..

How to do so?

**Comment by alenoosh** [comment]
@hopewise Your models should be added in the 'links' table so you should use the 'Links' section to add your models. Click on 'Add' button of 'Links' section, enter the label of your link in the 'Display' field of the form and the name of your model in the 'link' field of the form, after saving the data, the link will be displayed in the sidebar menu.

**Comment by hopewise** [comment]
Thank you! I hope this link table to get better documentation, "link" as a
word is a little bit far way from the real meaning, I think it should be
models instead of links..

Thank you

On Sun, Aug 30, 2015 at 2:16 PM, Alenoosh <notifications@github.com> wrote:

> @hopewise <https://github.com/hopewise> Your models should be added in
> the 'links' table so you should use the 'Links' section to add your models.
> Click on 'Add' button of 'Links' section, enter the label of your link in
> the 'Display' field of the form and the name of your model in the 'link'
> field of the form, after saving the data, the link will be displayed in the
> sidebar menu.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serverfireteam/panel/issues/87#issuecomment-136129336>
> .
>



-- 
--
Kind Regards,
---------------------------------------------
Samir Sabri
Software Architect& Developer
www.dcaclab.com
Jordan-Middle East

**Comment by alenoosh** [comment]
@hopewise You're welcome. Right now the links are bound to models but in future we may define links that are not bound to a model. That's why the 'Link' term is used. If you have any comments or suggestions about our panel, please feel free to let us know.
