### ISSUE TITLE
LaravelPanel authentication system doesn't respect apps with a non-default namespace set. 

### ISSUE THREAD

**Issue by DeftNerd** [serverfireteam/panel#9]
If you set your application namespace to something other than the default App the LaravelPanel authentication doesn't work. 

For example:
Run: php artisan app:name Test
Go to: http://localhost:8000/panel/login
Result:
FatalErrorException in AuthController.php line 6:
Class 'App\Http\Controllers\Controller' not found

Changing it back:
Run: php artisan app:name App
Go to: http://localhost:8000/panel/login

Everything works

**Comment by DeftNerd** [comment]
Interestingly enough, if you're already logged in and change the namespace, everything works fine. It's just the authentication and login/logout components.

**Comment by serverfire** [comment]
Thank you for report , now it is fixed 
608c1f24cc07749b222599eeb440b8a050bdd9a4
If you are using dev-master you will have the fix , @alenoosh  will relese a version if you are using version base .
