### ISSUE TITLE
Sidebar class="powered-by" CSS bug

### ISSUE THREAD

**Issue by Globax** [serverfireteam/panel#92]
id="side-menu" is go over the class="powered-by" http://prntscr.com/8bt7w8

**Comment by serverfire** [comment]
@Globax  Could you send fix for that ?

**Comment by Globax** [comment]
@serverfire I tried to fix that, but can't get it..

**Comment by serverfire** [comment]
@Globax  you can update from master branch and get this fix or wait for next version  release .

Thank you for reporting this bug.

**Comment by Globax** [comment]
@serverfire I was updated style.css file, but still have this bug, maybe it is because i use Dropdown (sb-admin)? http://sendvid.com/pcqufdau

**Comment by serverfire** [comment]
@Globax  some how is not updated for you , the power by text should be in white part of page . make sure you have last version

**Comment by Globax** [comment]
@serverfire Yeah, now it is in white part of page, I needed use this "php artisan vendor:publish --force" instead of "php artisan vendor:publish"..

But now it looks that: http://prntscr.com/8cvxp5

I think it would be better if the white part of page will scrolled with menu side.

**Comment by serverfire** [comment]
@Globax  fixed , please update from master

**Comment by Globax** [comment]
@serverfire Hmm, i replace this https://github.com/serverfireteam/panel/commit/7d6326a47cb97c6d5a767bbc4a1abe012abf66a6 , but have no changes

**Comment by serverfire** [comment]
@Globax  please make sure , for me it work

**Comment by Globax** [comment]
@serverfire http://sendvid.com/bxaxwm53

**Comment by serverfire** [comment]
@Globax the problem here is you are using that type of menu , 

to fix for you you need write a code to recalculate the height of page . like what we have in sb-admin-2.js

**Comment by Globax** [comment]
@serverfire Hmm, i use sb-admin dropdown, and how can i recalculate page height?

**Comment by serverfire** [comment]
@Globax Try to update to last sb-admin js file and see if it fix , see the sb-admin.js it only do that

**Comment by Globax** [comment]
@serverfire Update again sb-admin-2.js from your server, and have nothing..

**Comment by serverfire** [comment]
@Globax  as you can see in this pic this a bug from sb-admin 

I have put few hours on it to fix it , it did not fixed , you should have smaller menu , maybe more category 
![untitled](https://cloud.githubusercontent.com/assets/132761/9759916/ee2f5724-5705-11e5-83a6-b2025fbf945a.png)

**Comment by Globax** [comment]
@serverfire This is stupid :D Ok, tnx you very much :)
