### ISSUE TITLE
Laravel Panel Installation Problem

### ISSUE THREAD

**Issue by rajjora18** [serverfireteam/panel#94]
{
    "require": {
        "serverfireteam/panel": "1.2.*"
    },
}

D:\UniServerZ\www\ladmin5>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/support v5.1.8 requires php >=5.5.9 -> your PHP version (5.4.37
) or "config.platform.php" value does not satisfy that requirement.
    - illuminate/support v5.1.6 requires php >=5.5.9 -> your PHP version (5.4.37
) or "config.platform.php" value does not satisfy that requirement.
    - illuminate/support v5.1.2 requires php >=5.5.9 -> your PHP version (5.4.37
) or "config.platform.php" value does not satisfy that requirement.
    - illuminate/support v5.1.13 requires php >=5.5.9 -> your PHP version (5.4.3
7) or "config.platform.php" value does not satisfy that requirement.
    - illuminate/support v5.1.1 requires php >=5.5.9 -> your PHP version (5.4.37
) or "config.platform.php" value does not satisfy that requirement.
    - serverfireteam/blog dev-master requires illuminate/support ~5.1 -> satisfi
able by illuminate/support[v5.1.1, v5.1.13, v5.1.2, v5.1.6, v5.1.8].
    - Installation request for serverfireteam/blog dev-master -> satisfiable by
serverfireteam/blog[dev-master].

**Comment by serverfire** [comment]
@rajjora18 do you want install blog in laravel 5.0 ? or just panel in laravel 5.0 ?

**Comment by rajjora18** [comment]
Is, laravelpanel package works on laravel 4.2 or not ??

**Comment by serverfire** [comment]
@rajjora18  we did drop support of laravel 4.2 you can install laravel panel 1.1.* for laravel 4.2 

Thank you for using LaravelPanel
