### ISSUE TITLE
Installation prompts

### ISSUE THREAD

**Issue by marvinosswald** [serverfireteam/panel#98]
The installation routine prompts confirmation for 
- migrate
- seed

But it seems to ignore if i use it with `-n` can't answer the prompts on a automated deploy..

**Comment by serverfire** [comment]
@marvinosswald  yes right now it is not possible to confirmation for seed and migrate , you could just use manual install .

if you think we need ask user in prompts , please send a pull request so we can add that to package 

Thank you
