### ISSUE TITLE
Can't test with panel

### ISSUE THREAD

**Issue by marvinosswald** [serverfireteam/panel#99]
These lines in `config/elfinder.php` are getting redefined on each test, had to remove them to test again..

		function validName($name) {
			return strpos($name, '.') !== 0;
		}

		function access($attr, $path, $data, $volume) {
			if (strpos(basename($path), '.') === 0) {
			        return !($attr == 'read');
			} else {
			        return null;
			}
		}

**Comment by serverfire** [comment]
@marvinosswald I've fixed this bug, please get the latest updates. Thanks for reporting this bug.

**Comment by marvinosswald** [comment]
Awesome fast fix :+1:
